DELETE FROM diva_game_session WHERE pd_id IS NULL;
DELETE FROM diva_play_log WHERE pd_id IS NULL;
DELETE FROM diva_player_contest WHERE pd_id IS NULL;
DELETE FROM diva_player_customize WHERE pd_id IS NULL;
DELETE FROM diva_player_inventory WHERE pd_id IS NULL;
DELETE FROM diva_player_module WHERE pd_id IS NULL;
DELETE FROM diva_player_pv_customize WHERE pd_id IS NULL;
DELETE FROM diva_player_pv_record WHERE pd_id IS NULL;
DELETE FROM diva_player_screen_shot WHERE pd_id IS NULL;
DELETE FROM chuni_user_activity WHERE user_id IS NULL;
DELETE FROM chuni_user_character WHERE user_id IS NULL;
DELETE FROM chuni_user_charge WHERE user_id IS NULL;
DELETE FROM chuni_user_course WHERE user_id IS NULL;
DELETE FROM chuni_user_data_ex WHERE user_id IS NULL;
DELETE FROM chuni_user_duel WHERE user_id IS NULL;
DELETE FROM chuni_user_game_option WHERE user_id IS NULL;
DELETE FROM chuni_user_game_option_ex WHERE user_id IS NULL;
DELETE FROM chuni_user_general_data WHERE user_id IS NULL;
DELETE FROM chuni_user_item WHERE user_id IS NULL;
DELETE FROM chuni_user_map WHERE user_id IS NULL;
DELETE FROM chuni_user_music_detail WHERE user_id IS NULL;
DELETE FROM chuni_user_playlog WHERE user_id IS NULL;
DELETE FROM chusan_user_activity WHERE user_id IS NULL;
DELETE FROM chusan_user_character WHERE user_id IS NULL;
DELETE FROM chusan_user_charge WHERE user_id IS NULL;
DELETE FROM chusan_user_course WHERE user_id IS NULL;
DELETE FROM chusan_user_duel WHERE user_id IS NULL;
DELETE FROM chusan_user_gacha WHERE user_id IS NULL;
DELETE FROM chusan_user_game_option WHERE user_id IS NULL;
DELETE FROM chusan_user_general_data WHERE user_id IS NULL;
DELETE FROM chusan_user_item WHERE user_id IS NULL;
DELETE FROM chusan_user_map_area WHERE user_id IS NULL;
DELETE FROM chusan_user_music_detail WHERE user_id IS NULL;
DELETE FROM chusan_user_playlog WHERE user_id IS NULL;
DELETE FROM chusan_user_print_state WHERE user_id IS NULL;
DELETE FROM maimai2_user_activity WHERE user_id IS NULL;
DELETE FROM maimai2_user_card WHERE user_id IS NULL;
DELETE FROM maimai2_user_character WHERE user_id IS NULL;
DELETE FROM maimai2_user_charge WHERE user_id IS NULL;
DELETE FROM maimai2_user_course WHERE user_id IS NULL;
DELETE FROM maimai2_user_extend WHERE user_id IS NULL;
DELETE FROM maimai2_user_favorite WHERE user_id IS NULL;
DELETE FROM maimai2_user_friend_season_ranking WHERE user_id IS NULL;
DELETE FROM maimai2_user_general_data WHERE user_id IS NULL;
DELETE FROM maimai2_user_item WHERE user_id IS NULL;
DELETE FROM maimai2_user_login_bonus WHERE user_id IS NULL;
DELETE FROM maimai2_user_map WHERE user_id IS NULL;
DELETE FROM maimai2_user_music_detail WHERE user_id IS NULL;
DELETE FROM maimai2_user_npc_encount WHERE user_id IS NULL;
DELETE FROM maimai2_user_option WHERE user_id IS NULL;
DELETE FROM maimai2_user_playlog WHERE user_id IS NULL;
DELETE FROM maimai2_user_print_detail WHERE user_id IS NULL;
DELETE FROM maimai2_user_udemae WHERE user_id IS NULL;
DELETE FROM maimai_user_activity WHERE user_id IS NULL;
DELETE FROM maimai_user_boss WHERE user_id IS NULL;
DELETE FROM maimai_user_character WHERE user_id IS NULL;
DELETE FROM maimai_user_general_data WHERE user_id IS NULL;
DELETE FROM maimai_user_item WHERE user_id IS NULL;
DELETE FROM maimai_user_music_detail WHERE user_id IS NULL;
DELETE FROM maimai_user_option WHERE user_id IS NULL;
DELETE FROM maimai_user_playlog WHERE user_id IS NULL;
DELETE FROM maimai_user_present_event WHERE user_id IS NULL;
DELETE FROM maimai_user_survival WHERE user_id IS NULL;
DELETE FROM maimai_user_web_option WHERE user_id IS NULL;
DELETE FROM ongeki_user_activity WHERE user_id IS NULL;
DELETE FROM ongeki_user_boss WHERE user_id IS NULL;
DELETE FROM ongeki_user_card WHERE user_id IS NULL;
DELETE FROM ongeki_user_chapter WHERE user_id IS NULL;
DELETE FROM ongeki_user_character WHERE user_id IS NULL;
DELETE FROM ongeki_user_deck WHERE user_id IS NULL;
DELETE FROM ongeki_user_event_music WHERE user_id IS NULL;
DELETE FROM ongeki_user_event_point WHERE user_id IS NULL;
DELETE FROM ongeki_user_general_data WHERE user_id IS NULL;
DELETE FROM ongeki_user_item WHERE user_id IS NULL;
DELETE FROM ongeki_user_kop WHERE user_id IS NULL;
DELETE FROM ongeki_user_login_bonus WHERE user_id IS NULL;
DELETE FROM ongeki_user_memory_chapter WHERE user_id IS NULL;
DELETE FROM ongeki_user_mission_point WHERE user_id IS NULL;
DELETE FROM ongeki_user_music_detail WHERE user_id IS NULL;
DELETE FROM ongeki_user_music_item WHERE user_id IS NULL;
DELETE FROM ongeki_user_option WHERE user_id IS NULL;
DELETE FROM ongeki_user_playlog WHERE user_id IS NULL;
DELETE FROM ongeki_user_rival WHERE user_id IS NULL;
DELETE FROM ongeki_user_scenario WHERE user_id IS NULL;
DELETE FROM ongeki_user_story WHERE user_id IS NULL;
DELETE FROM ongeki_user_tech_count WHERE user_id IS NULL;
DELETE FROM ongeki_user_tech_event WHERE user_id IS NULL;
DELETE FROM ongeki_user_trade_item WHERE user_id IS NULL;
DELETE FROM ongeki_user_training_room WHERE user_id IS NULL;

ALTER TABLE diva_game_session MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_play_log MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_contest MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_customize MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_inventory MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_module MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_pv_customize MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_pv_record MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE diva_player_screen_shot MODIFY pd_id BIGINT NOT NULL;
ALTER TABLE chuni_user_activity MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_character MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_charge MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_course MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_data_ex MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_duel MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_game_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_game_option_ex MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_general_data MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_map MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_music_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chuni_user_playlog MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_activity MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_character MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_charge MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_course MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_duel MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_gacha MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_game_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_general_data MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_map_area MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_music_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_playlog MODIFY user_id BIGINT NOT NULL;
ALTER TABLE chusan_user_print_state MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_activity MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_card MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_character MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_charge MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_course MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_extend MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_favorite MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_friend_season_ranking MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_general_data MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_login_bonus MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_map MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_music_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_npc_encount MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_playlog MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_print_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai2_user_udemae MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_activity MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_boss MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_character MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_general_data MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_music_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_playlog MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_present_event MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_survival MODIFY user_id BIGINT NOT NULL;
ALTER TABLE maimai_user_web_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_activity MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_boss MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_card MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_chapter MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_character MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_deck MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_event_music MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_event_point MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_general_data MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_kop MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_login_bonus MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_memory_chapter MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_mission_point MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_music_detail MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_music_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_option MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_playlog MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_rival MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_scenario MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_story MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_tech_count MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_tech_event MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_trade_item MODIFY user_id BIGINT NOT NULL;
ALTER TABLE ongeki_user_training_room MODIFY user_id BIGINT NOT NULL;
