INSERT INTO chusan_voice (id, name) VALUES (1, 'チュウニペンギン');
INSERT INTO chusan_voice (id, name) VALUES (2, 'G．O．D');
INSERT INTO chusan_voice (id, name) VALUES (3, '月鈴 白奈');
INSERT INTO chusan_voice (id, name) VALUES (4, '箱部 なる');
INSERT INTO chusan_voice (id, name) VALUES (5, 'スザク');
INSERT INTO chusan_voice (id, name) VALUES (6, '天王洲 なずな');
INSERT INTO chusan_voice (id, name) VALUES (7, '明坂 芹菜');
INSERT INTO chusan_voice (id, name) VALUES (8, 'トリスメギストス');
INSERT INTO chusan_voice (id, name) VALUES (9, 'MIR-202【アルテミス・レナ】');
INSERT INTO chusan_voice (id, name) VALUES (10, '小仏 凪');
INSERT INTO chusan_voice (id, name) VALUES (11, '御形 アリシアナ');
INSERT INTO chusan_voice (id, name) VALUES (12, 'リリアリス・コルチカム');
INSERT INTO chusan_voice (id, name) VALUES (13, '月鈴 那知');
INSERT INTO chusan_voice (id, name) VALUES (14, 'リヒトシュッツェ');
INSERT INTO chusan_voice (id, name) VALUES (15, 'HAR-ヒロイン09【ネレイダム】');
INSERT INTO chusan_voice (id, name) VALUES (16, '五十嵐 撫子');
INSERT INTO chusan_voice (id, name) VALUES (17, 'ダオ・トッテナ');
INSERT INTO chusan_voice (id, name) VALUES (18, '萩原 七々瀬');
INSERT INTO chusan_voice (id, name) VALUES (19, '八咫烏 鋼太郎');
INSERT INTO chusan_voice (id, name) VALUES (20, '黒亀 北斗');
INSERT INTO chusan_voice (id, name) VALUES (21, '暴虐のギーゼグール');
INSERT INTO chusan_voice (id, name) VALUES (22, '小野 美苗');
INSERT INTO chusan_voice (id, name) VALUES (23, '渋沢 ノノ');
INSERT INTO chusan_voice (id, name) VALUES (24, '葛城 華');
INSERT INTO chusan_voice (id, name) VALUES (25, '新井 桃子');
INSERT INTO chusan_voice (id, name) VALUES (26, 'MIR-201【ヘカティ・ベアトリクス】');
INSERT INTO chusan_voice (id, name) VALUES (27, 'テスタメントネメシス');
INSERT INTO chusan_voice (id, name) VALUES (28, 'DJ-MEGA');
INSERT INTO chusan_voice (id, name) VALUES (29, '藤堂 陽南袴');
INSERT INTO chusan_voice (id, name) VALUES (30, '桔梗 小夜曲');
INSERT INTO chusan_voice (id, name) VALUES (31, 'MDA-01【シリウス】');
INSERT INTO chusan_voice (id, name) VALUES (32, '芒崎 奏');
INSERT INTO chusan_voice (id, name) VALUES (33, 'ティフォン');
INSERT INTO chusan_voice (id, name) VALUES (34, 'イングリット・オーリック・コーネル');
INSERT INTO chusan_voice (id, name) VALUES (35, 'シルヴィアス');
INSERT INTO chusan_voice (id, name) VALUES (36, 'ジョニー・サイアスティン');
INSERT INTO chusan_voice (id, name) VALUES (37, '魔法使いアルテラ');
INSERT INTO chusan_voice (id, name) VALUES (38, '新田 ちえ');
INSERT INTO chusan_voice (id, name) VALUES (39, 'MDA-21【レグルス】');
INSERT INTO chusan_voice (id, name) VALUES (40, 'ジュナ・サラキア');
INSERT INTO chusan_voice (id, name) VALUES (43, 'ワイズマン');
INSERT INTO chusan_voice (id, name) VALUES (44, 'ヴェルゼビュートネメシス');
