//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaMai.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AquaMai.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded!.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected while loading!
        ///- Check if you have installed the wrong version of AquaMai, such as using SDEZ version on SDGA
        ///- Are you using a modified Assembly-CSharp.dll, which will cause inconsistent functions and cannot find the functions that need to be modified
        ///- Check for conflicting mods, or enabled incompatible options.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string MarkRepeatEnd {
            get {
                return ResourceManager.GetString("MarkRepeatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string MarkRepeatStart {
            get {
                return ResourceManager.GetString("MarkRepeatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime reader error.
        /// </summary>
        internal static string NetErrIsAliveAimeReader {
            get {
                return ResourceManager.GetString("NetErrIsAliveAimeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime server error.
        /// </summary>
        internal static string NetErrIsAliveAimeServer {
            get {
                return ResourceManager.GetString("NetErrIsAliveAimeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication error.
        /// </summary>
        internal static string NetErrIsAliveServer {
            get {
                return ResourceManager.GetString("NetErrIsAliveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data download not success.
        /// </summary>
        internal static string NetErrWasDownloadSuccessOnce {
            get {
                return ResourceManager.GetString("NetErrWasDownloadSuccessOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS+ =&gt; DXRating += {0}.
        /// </summary>
        internal static string RatingUpWhenSSSp {
            get {
                return ResourceManager.GetString("RatingUpWhenSSSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Not Set.
        /// </summary>
        internal static string RepeatNotSet {
            get {
                return ResourceManager.GetString("RepeatNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RepeatReset {
            get {
                return ResourceManager.GetString("RepeatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Set.
        /// </summary>
        internal static string RepeatStartEndSet {
            get {
                return ResourceManager.GetString("RepeatStartEndSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Start Set.
        /// </summary>
        internal static string RepeatStartSet {
            get {
                return ResourceManager.GetString("RepeatStartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving... Do not exit the game.
        /// </summary>
        internal static string SavingDontExit {
            get {
                return ResourceManager.GetString("SavingDontExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek &lt;&lt;.
        /// </summary>
        internal static string SeekBackward {
            get {
                return ResourceManager.GetString("SeekBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek &gt;&gt;.
        /// </summary>
        internal static string SeekForward {
            get {
                return ResourceManager.GetString("SeekForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed -.
        /// </summary>
        internal static string SpeedDown {
            get {
                return ResourceManager.GetString("SpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Reset.
        /// </summary>
        internal static string SpeedReset {
            get {
                return ResourceManager.GetString("SpeedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed +.
        /// </summary>
        internal static string SpeedUp {
            get {
                return ResourceManager.GetString("SpeedUp", resourceCulture);
            }
        }
    }
}
