INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (183, 'ELISA「ef - a tale of memories.」', '楽曲「euphoric field（English）」', 0, 'euphoric field（English）', 'v1 1.45.00', 'EUPHORICFIELDENGLISH');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (333, 't+pazolite', 'なし', 9, 'Oshama Scramble!', 'v1 1.45.00', 'OSHAMASCRAMBLE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (429, 'wa.', 'なし', 6, 'Black Lotus', 'v1 1.40.00', 'BLACKLOTUS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (809, 'GARNiDELiA「魔法科高校の劣等生」', '楽曲「grilletto」', 0, 'grilletto', 'v1 1.40.00', 'GRILLETTO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (810, 'OxT「SSSS.GRIDMAN」', 'SSSS.GRIDMAN', 0, 'UNION', 'v1 1.40.00', 'UNION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (811, '米津玄師', '楽曲「Lemon」「紅蓮華」', 0, 'Lemon', 'v1 1.40.00', 'LEMON');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (812, 'ALTIMA「アクセル・ワールド」', 'なし', 0, 'BURST THE GRAVITY', 'v1 1.40.00', 'BURSTTHEGRAVITY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (813, 'Division All Stars「ヒプノシスマイク」', '楽曲「ヒプノシスマイク -Division Battle Anthem-」', 0, 'ヒプノシスマイク -Division Battle Anthem-', 'v1 1.40.00', 'ヒフノシスマイクDIVISIONBATTLEANTHEM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (814, '麻帆良学園中等部2-A「魔法先生ネギま！」', '楽曲「ハッピー☆マテリアル」', 0, 'ハッピー☆マテリアル', 'v1 1.40.00', 'ハツヒウマテリアル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (815, 'ヨルシカ', 'なし', 0, 'ただ君に晴れ', 'v1 1.40.00', 'タタキミニハレ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (816, 'Eve', '楽曲「ナンセンス文学」', 2, 'ナンセンス文学', 'v1 1.40.00', 'ナンセンスフンカク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (817, 'じん', 'なし', 2, 'ロスタイムメモリー', 'v1 1.40.00', 'ロスタイムメモリウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (818, 'DECO*27', '初音ミク関連', 2, 'ヒバナ', 'v1 1.40.00', 'ヒハナ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (819, 'ビートまりお(COOL＆CREATE)', '東方Project関連', 3, '最終鬼畜妹フランドール・S', 'v1 1.40.00', 'サイシユウキチクイモウトフラントウルスカウレツト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (821, 'HaNaMiNa feat.Nadeshiko', 'なし', 7, '"STAR"T', 'v1 1.40.00', 'START');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (822, 'Project Grimoire', 'なし', 9, 'Excalibur ～Revived resolution～', 'v1 1.40.00', 'EXCALIBURREVIVEDRESOLUTION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (823, 'かねこちはる', 'なし', 9, 'Opfer', 'v1 1.40.00', 'OPFER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (824, 'NAOKI MAEDA', 'なし', 5, '神威 (NAOKI × ZPP MIX)', 'v1 1.40.00', 'カムイNAOKIZPPMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (825, 'じーざす（ワンダフル☆オポチュニティ！） ft.96猫', 'なし', 5, 'サヴァイバル・キリング・メーカー', 'v1 1.40.00', 'サウアイハルキリンクメウカウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (826, 'ユリイ・カノン feat.nameless', 'なし', 5, 'ツクヨミステップ', 'v1 1.40.00', 'ツクヨミステツフ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (827, '溝口ゆうま axel. 大瀬良あい', 'なし', 5, '【冒険】イングリット葛西降臨！【実況】', 'v1 1.40.00', 'インクリツトカサイコウリン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (828, 'ゆゆうた', 'なし', 5, 'ハジマリノピアノ', 'v1 1.40.00', 'ハシマリノヒアノ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (829, 'かいりきベア feat.松下', 'なし', 5, 'レーイレーイ', 'v1 1.40.00', 'レウイレウイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (830, '石渡太輔／アークシステムワークス', 'なし', 5, 'Surrogate Life', 'v1 1.40.00', 'SURROGATELIFE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (831, 'yukitani', 'なし', 5, 'Nijirate Fanatics', 'v1 1.40.00', 'NIJIRATEFANATICS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (832, '削除 feat. Nikki Simmons', 'なし', 6, 'Destr0yer', 'v1 1.40.00', 'DESTR0YER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (833, 'eicateve', 'なし', 6, 'R.I.P.', 'v1 1.40.00', 'RIP');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (834, '立秋', 'なし', 5, 'せかいせいふく！ゆりあちゃん！', 'v1 1.40.00', 'セカイセイフクユリアチヤン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (835, 'Noah', 'なし', 5, 'Trackless wilderness', 'v1 1.40.00', 'TRACKLESSWILDERNESS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (836, 'Acotto', 'なし', 5, 'absolute rightness', 'v1 1.40.00', 'ABSOLUTERIGHTNESS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (837, 'Aoi Sumito', 'なし', 5, 'Walzer für das Nichts', 'v1 1.40.00', 'WALZERFURDASNICHTS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (838, 'litmus*', 'なし', 5, 'Lover''s Trick', 'v1 1.40.00', 'LOVERSTRICK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (839, 'Yu-dachi', 'なし', 5, 'まごころのカスクルゥト', 'v1 1.40.00', 'マココロノカスクルウト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (840, 'なきゃむりゃ', '結月ゆかり関連', 2, '幾望の月', 'v1 1.40.00', 'キホウノツキ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (841, 'GYARI', '楽曲「アカリがやってきたぞっ」', 2, 'アカリがやってきたぞっ', 'v1 1.40.00', 'アカリカヤツテキタソツ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (842, 'ONE (song by ナナホシ管弦楽団)', '楽曲「おねがいダーリン」', 2, 'おねがいダーリン', 'v1 1.40.00', 'オネカイタウリン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (843, 'kemu', 'なし', 2, 'リンカーネイション', 'v1 1.40.00', 'リンカウネイシヨン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (844, 'ナユタン星人', 'なし', 2, '太陽系デスコ', 'v1 1.40.00', 'タイヨウケイテスコ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (845, 'KOTOKO「ネコぱら」', 'ネコぱら', 0, '▲MEW▲△MEW△CAKE', 'v1 1.40.00', 'MEWMEWCAKE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (846, 'パトリシア・オブ・エンド(CV：高森奈津美)、黒木 未知(CV：仙台エリ)、夕莉 シャチ(CV：浅川悠)、明日原 ユウキ(CV：種﨑敦美)「ノラと皇女と野良猫ハート」', 'ノラと皇女と野良猫ハート', 0, '野良猫ハート', 'v1 1.40.00', 'ノラネコハウト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (847, '小倉 唯「変態王子と笑わない猫。」', 'キングレコード楽曲関連', 0, 'Baby Sweet Berry Love', 'v1 1.40.00', 'BABYSWEETBERRYLOVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (848, 'sumijun(Halozy) feat. ななひら(Confetto)', '東方Project関連', 3, '進捗どうですか？', 'v1 1.40.00', 'シンチヨクトウテスカ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (849, '葛城 華(CV:丸岡 和佳奈)', 'なし', 7, '単一指向性オーバーブルーム', 'v1 1.40.00', 'タンイツシコウセイオウハウフルウム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (850, 'Norn', 'なし', 5, '《混乱》 ～ Muspell', 'v1 1.40.00', 'コンランMUSPELL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (851, 'Shi Kuang Lee feat.A-Tz', 'なし', 5, '《理想》 ～ Cloudland', 'v1 1.40.00', 'リソウCLOUDLAND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (852, 'Bo-Xun Lin 林柏勲', 'なし', 5, '《逃避》 ～ The Deserter', 'v1 1.40.00', 'トウヒTHEDESERTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (853, 'James Landino feat.N i i', 'なし', 5, '《最愛》 ～ Curse', 'v1 1.40.00', 'サイアイCURSE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (854, '3R2', 'なし', 5, '《運命》 ～ Ray of Hope', 'v1 1.40.00', 'ウンメイRAYOFHOPE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (855, 'Tia「賭ケグルイ」', '賭ケグルイ××', 0, 'Deal with the devil', 'v1 1.40.00', 'DEALWITHTHEDEVIL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (856, 'スタァライト九九組「少女☆歌劇 レヴュースタァライト」', '楽曲「Star Divine」', 0, 'Star Divine', 'v1 1.40.00', 'STARDIVINE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (857, '奥井雅美「少女革命ウテナ」', '楽曲「輪舞-revolution」', 0, '輪舞-revolution', 'v1 1.40.00', 'ロントREVOLUTION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (858, '「サクラ大戦３ ～巴里は燃えているか～」', 'なし', 6, '御旗のもとに', 'v1 1.40.00', 'ミハタノモトニ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (859, '小野 美苗(CV:伊藤 美来)', 'なし', 7, 'みなえをチェック！', 'v1 1.40.00', 'ミナエヲチエツク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (860, 'MOSAIC.WAV／t+pazolite feat.ななひら', 'なし', 5, 'とーきょー全域★アキハバラ？ (ver.にこる)', 'v1 1.40.00', 'トウキヨウセンイキアキハハラVERニコル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (861, 'わたてん☆5「私に天使が舞い降りた！」', '私に天使が舞い降りた！', 0, '気ままな天使たち', 'v1 1.40.00', 'キママナテンシタチ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (862, 'わたてん☆5「私に天使が舞い降りた！」', '私に天使が舞い降りた！', 0, 'ハッピー・ハッピー・フレンズ', 'v1 1.40.00', 'ハツヒウハツヒウフレンス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (863, '削除', 'なし', 6, 'AXION', 'v1 1.40.00', 'AXION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (865, 'BlackY vs. Yooh', 'なし', 9, 'MEGATON BLAST', 'v1 1.40.00', 'MEGATONBLAST');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (866, '岸田教団&THE明星ロケッツ「ストライク・ザ・ブラッド」', 'ストライク・ザ・ブラッド', 0, 'ストライク・ザ・ブラッド', 'v1 1.40.00', 'ストライクサフラツト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (867, 'ハチ', '初音ミク関連', 2, '結んで開いて羅刹と骸', 'v1 1.40.00', 'ムスンテヒライテラセツトムクロ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (868, 'アゴアニキ', '初音ミク関連', 2, 'ダブルラリアット', 'v1 1.40.00', 'タフルラリアツト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (869, 'sasakure.UK', '初音ミク関連', 2, '＊ハロー、プラネット。', 'v1 1.40.00', 'ハロウフラネツト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (870, 'minato(流星P)', '初音ミク関連', 2, 'magnet', 'v1 1.40.00', 'MAGNET');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (871, 'IOSYS TRAX (uno & D.watt)', '東方Project関連', 3, 'Pump!n', 'v1 1.40.00', 'PUMPIN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (872, 'A-One', '東方Project関連', 3, 'Endless Seeker', 'v1 1.40.00', 'ENDLESSSEEKER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (873, '発熱巫女～ず', '東方Project関連', 3, 'STRIPES feat. EL.J (2018 reinterpretation)', 'v1 1.40.00', 'STRIPESFEATELJ2018REINTERPRETATION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (874, 'SOUND HOLIC feat. Nana Takahashi', '東方Project関連', 3, 'Cosmic Magic Shooter', 'v1 1.40.00', 'COSMICMAGICSHOOTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (875, 'Liz Triangle', '東方Project関連', 3, '神楽', 'v1 1.40.00', 'カクラ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (876, 'Masayoshi Minoshima × Nhato', '東方Project関連', 3, 'Bad Apple!! feat.nomico (Nhato Remix)', 'v1 1.40.00', 'BADAPPLEFEATNOMICONHATOREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (877, '麹町養蚕館', 'なし', 5, 'ヴンダーカンマー', 'v1 1.40.00', 'ウンタウカンマウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (878, 'Nhato', 'なし', 5, 'Destination', 'v1 1.40.00', 'DESTINATION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (879, 'nora2r', 'なし', 5, 'Fidget Dancer', 'v1 1.40.00', 'FIDGETDANCER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (880, '削除', 'なし', 5, 'Megameteor', 'v1 1.40.00', 'MEGAMETEOR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (881, 's-don vs. 翡乃イスカ', 'なし', 5, 'Trrricksters!!', 'v1 1.40.00', 'TRRRICKSTERS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (882, 'HaNaMiNa feat.Nanase', 'なし', 7, 'Road without Road', 'v1 1.40.00', 'ROADWITHOUTROAD');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (883, 'フランシュシュ「ゾンビランドサガ」', 'ゾンビランドサガ', 0, '徒花ネクロマンシー', 'v1 1.40.00', 'アタハナネクロマンシウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (884, 'フランシュシュ「ゾンビランドサガ」', 'ゾンビランドサガ', 0, '目覚めRETURNER', 'v1 1.40.00', 'メサメRETURNER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (885, 'ESTi', 'なし', 6, 'Ladymade Star', 'v1 1.40.00', 'LADYMADESTAR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (886, 'M2U', 'なし', 6, 'Memory of Beach', 'v1 1.40.00', 'MEMORYOFBEACH');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (887, 'Hosoe Shinji', 'なし', 6, 'SON OF SUN', 'v1 1.40.00', 'SONOFSUN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (888, 'Mili「ゴブリンスレイヤー」', 'ゴブリンスレイヤー', 0, 'Rightfully', 'v1 1.40.00', 'RIGHTFULLY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (889, 'Chu☆', 'なし', 0, '巫女みこナース・愛のテーマ', 'v1 1.40.00', 'ミコミコナウスアイノテウマ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (890, 'FictionJunction YUUKA｢MADLAX｣', 'なし', 0, 'nowhere', 'v1 1.40.00', 'NOWHERE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (891, 'ゴリライザー制作委員会', 'なし', 6, '音弾超人ゴリライザー', 'v1 1.40.00', 'オンタンチヨウシンコリライサウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (892, 'ナノ「緋弾のアリアAA」', '緋弾のアリアAA', 0, 'Bull''s Eye', 'v1 1.40.00', 'BULLSEYE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (893, 'Sobrem a.k.a. Widowmaker', 'なし', 6, 'Giselle', 'v1 1.40.00', 'GISELLE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (894, 'Aliesrite* (Ym1024 feat. lamie*)', 'なし', 6, '7 colors*', 'v1 1.40.00', '7COLORS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (895, 'Junk', 'なし', 6, 'Life is PIANO', 'v1 1.40.00', 'LIFEISPIANO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (896, '曲：鯨井国家／歌：藍原 椿(CV：橋本 ちなみ)', 'なし', 9, 'タテマエと本心の大乱闘', 'v1 1.40.00', 'タテマエトホンシンノタイラントウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (897, '曲：上松範廉(Elements Garden)／歌：三角 葵(CV：春野 杏)', 'なし', 9, 'Zest of Blue', 'v1 1.40.00', 'ZESTOFBLUE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (899, 'イロドリミドリ', 'なし', 7, 'conflict(斉唱)', 'v1 1.45.00', 'CONFLICTセイシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (900, 'Bitplane', 'なし', 6, 'チョウの標本', 'v1 1.40.00', 'チヨウノヒヨウホン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (901, 'Sammy sound team', 'なし', 6, 'Be A Shooter！～NORMAL BIG BONUS～', 'v1 1.40.00', 'BEASHOOTERNORMALBIGBONUS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (902, '井口裕香「ダンジョンに出会いを求めるのは間違っているだろうかⅡ」', '楽曲「HELLO to DREAM」', 0, 'HELLO to DREAM', 'v1 1.45.00', 'HELLOTODREAM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (903, 'ヘスティア（CV:水瀬いのり）「ダンジョンに出会いを求めるのは間違っているだろうか」', '楽曲「君色Everyday」', 0, '君色Everyday', 'v1 1.45.00', 'キミイロEVERYDAY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (904, '紗倉ひびき（CV:ファイルーズあい）＆街雄鳴造（CV:石川界人）「ダンベル何キロ持てる？」', 'ダンベル何キロ持てる？', 0, 'お願いマッスル', 'v1 1.45.00', 'オネカイマツスル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (905, 'LiSA', '楽曲「Lemon」「紅蓮華」', 0, '紅蓮華', 'v1 1.45.00', 'クレンケ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (907, '中野家の五つ子（花澤香菜・竹達彩奈・伊藤美来・佐倉綾音・水瀬いのり） TVアニメ「五等分の花嫁」', 'なし', 0, '五等分の気持ち', 'v1 1.45.00', 'コトウフンノキモチ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (908, '涼宮ハルヒ（CV.平野 綾） TVアニメ「涼宮ハルヒの憂鬱」', '楽曲「ハレ晴レユカイ」「God knows...」', 0, 'God knows...', 'v1 1.45.00', 'GODKNOWS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (909, 'livetune', '初音ミク関連', 2, 'Catch the Wave', 'v1 1.45.00', 'CATCHTHEWAVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (910, 'ginkiha「Arcaea」', 'Arcaea', 6, 'Auxesia', 'v1 1.45.00', 'AUXESIA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (911, 'Laur', 'なし', 6, 'Sound Chimera', 'v1 1.45.00', 'SOUNDCHIMERA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (912, '小仏 凪(CV:佐倉 薫)＆月鈴 白奈(CV:高野 麻里佳)', 'なし', 7, 'やらなきゃいけないことばかり', 'v1 1.45.00', 'ヤラナキヤイケナイコトハカリ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (913, 'イロドリミドリ', 'なし', 7, 'エンドマークに希望と涙を添えて ～イロドリミドリアレンジ～', 'v1 1.45.00', 'エントマウクニキホウトナミタヲソエテイロトリミトリアレンシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (914, '島爺×蜂屋ななし', 'なし', 9, 'Secret Sleuth', 'v1 1.45.00', 'SECRETSLEUTH');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (915, '亜沙 feat.くろくも', 'なし', 5, 'Ghost Dance', 'v1 1.45.00', 'GHOSTDANCE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (916, 'カラフル・サウンズ・ポート', 'なし', 5, 'モノクロトワイライト', 'v1 1.45.00', 'モノクロトワイライト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (917, '黒魔', 'なし', 5, 'シャッキーーン！！', 'v1 1.45.00', 'シヤツキウウン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (918, 'Spiegel vs Ice', 'なし', 5, '《破滅》 ～ Rhapsody for The End', 'v1 1.45.00', 'ハメツRHAPSODYFORTHEEND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (919, '山崎寛子「白猫プロジェクト」', '白猫プロジェクト', 0, 'Ray ―はじまりのセカイ― (クロニクルアレンジver.)', 'v1 1.45.00', 'RAYハシマリノセカイクロニクルアレンシVER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (920, '「白猫プロジェクト」', '白猫プロジェクト', 0, '狩猟戦旗～REQUIEM', 'v1 1.45.00', 'シユリヨウセンキREQUIEM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (921, 'はるまきごはん', 'なし', 2, 'メルティランドナイトメア', 'v1 1.45.00', 'メルテイラントナイトメア');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (922, 'GYARI', '楽曲「絶対にチョコミントを食べるアオイチャン」', 2, '絶対にチョコミントを食べるアオイチャン', 'v1 1.45.00', 'セツタイニチヨコミントヲタヘルアオイチヤン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (923, 'ユリイ・カノン', 'なし', 2, 'だれかの心臓になれたなら', 'v1 1.45.00', 'タレカノシンソウニナレタナラ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (924, 'らき・あいね・みお from BEST FRIENDS！/わか・るか・せな「アイカツオンパレード！」', 'アイカツオンパレード！', 0, 'アイドル活動！オンパレード！ver.', 'v1 1.45.00', 'アイトルカツトウオンハレウトVER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (925, 'わか・ふうり・すなお from STAR☆ANIS「アイカツ！」', 'アイカツオンパレード！', 0, 'ダイヤモンドハッピー', 'v1 1.45.00', 'タイヤモントハツヒウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (926, '榊原 ゆい「Dies irae」', '楽曲「Kadenz」', 0, 'Kadenz', 'v1 1.45.00', 'KADENZ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (927, 'LeaF & Optie & Fiz', 'なし', 6, 'MARENOL', 'v1 1.45.00', 'MARENOL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (928, '御形 アリシアナ(CV:福原 綾香)＆箱部 なる(CV:M・A・O)', 'なし', 7, 'Day by Day CRiSiS Songs', 'v1 1.45.00', 'DAYBYDAYCRISISSONGS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (929, '激戦の人', '東方Project関連', 3, 'Energy Booster ～ 上海紅茶館', 'v1 1.45.00', 'ENERGYBOOSTERシヤンハイコウチヤカン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (930, 'Silver Forest', '東方Project関連', 3, '7 days a week', 'v1 1.45.00', '7DAYSAWEEK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (931, '岸田教団&THE明星ロケッツ', '東方Project関連', 3, 'メイドと血の懐中時計', 'v1 1.45.00', 'メイトトチノカイチユウトケイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (932, 'Alstroemeria Records', '東方Project関連', 3, 'ARROW RAIN feat. Ayame', 'v1 1.45.00', 'ARROWRAINFEATAYAME');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (933, '森羅万象', '東方Project関連', 3, '悪戯センセーション', 'v1 1.45.00', 'イタスラセンセウシヨン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (934, '月鈴 白奈(CV:高野 麻里佳)', 'なし', 7, '紅き魔汁、闇より降りて天啓の響きを導く', 'v1 1.45.00', 'アカキマシユウヤミヨリオリテテンケイノヒヒキヲミチヒク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (935, 'はるまきごはん feat.めらみぽっぷ', 'なし', 5, 'ロング・スロー・アライブ', 'v1 1.45.00', 'ロンクスロウアライフ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (936, 'YM feat.かんせる', 'なし', 5, '迷える薔薇に終わらぬ夜を', 'v1 1.45.00', 'マヨエルハラニオワラヌヨルヲ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (937, 'ポリスピカデリー feat.相宮零', 'なし', 5, 'パームカルマ', 'v1 1.45.00', 'ハウムカルマ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (938, 'うどんゲルゲ', 'なし', 5, 'Therapeutic Hoedown', 'v1 1.45.00', 'THERAPEUTICHOEDOWN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (939, '八王子P「#コンパス」', '#コンパス', 2, 'バイオレンストリガー', 'v1 1.45.00', 'ハイオレンストリカウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (940, '梅とら「#コンパス」', '#コンパス', 2, 'KILLER B', 'v1 1.45.00', 'KILLERB');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (941, 'buzzG「#コンパス」', '楽曲「レトロマニア狂想曲」「クレイジー・ビート」', 2, 'アヤカシ', 'v1 1.45.00', 'アヤカシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (942, '164「#コンパス」', '#コンパス', 2, '残響', 'v1 1.45.00', 'サンキヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (943, 'さつき が てんこもり「#コンパス」', '楽曲「レトロマニア狂想曲」「クレイジー・ビート」', 2, 'クレイジー・ビート', 'v1 1.45.00', 'クレイシウヒウト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (944, 'onoken', 'なし', 6, 'felys -final remix-', 'v1 1.45.00', 'FELYSFINALREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (945, '明坂 芹菜(CV:新田 恵海)＆天王洲 なずな(CV:山本 彩乃)', 'なし', 7, 'アフタースクール・エモーション', 'v1 1.45.00', 'アフタウスクウルエモウシヨン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (946, 'owl＊tree feat.yu＊tree', 'なし', 5, 'Jörqer', 'v1 1.45.00', 'JORQER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (947, 'さつき が てんこもり feat.kana', 'なし', 5, 'ちゅんちゅちゅチューン', 'v1 1.45.00', 'チユンチユチユチユウン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (948, 'コバヤシユウヤ（IOSYS） feat.You-Re:', 'なし', 5, 'ドルオタ忍道！楠子ノ巻', 'v1 1.45.00', 'トルオタニントウナンコノマキ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (949, 'Clean Tears feat.kukuri', 'なし', 5, 'エキセントリックコンコン', 'v1 1.45.00', 'エキセントリツクコンコン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (950, 'MOSAIC.WAV', 'なし', 5, '大天使ユリア★降臨!', 'v1 1.45.00', 'タイテンシユリアコウリン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (951, 'HUiT「八月のシンデレラナイン」', '八月のシンデレラナイン', 0, 'かっとばせ！未来へ', 'v1 1.45.00', 'カツトハセミライヘ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (952, 'Clutch!「八月のシンデレラナイン」', '八月のシンデレラナイン', 0, 'ALL FOR ONE★', 'v1 1.45.00', 'ALLFORONE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (953, 'Omoi', '初音ミク関連', 2, 'グリーンライツ・セレナーデ', 'v1 1.45.00', 'クリウンライツセレナウテ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (954, '和田たけあき', '初音ミク関連', 2, 'ブレス・ユア・ブレス', 'v1 1.45.00', 'フレスユアフレス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (955, 'EasyPop', '初音ミク関連', 2, 'Jump for Joy', 'v1 1.45.00', 'JUMPFORJOY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (956, '分島花音「selector infected WIXOSS」', '楽曲「killy killy JOKER」', 0, 'killy killy JOKER', 'v1 1.45.00', 'KILLYKILLYJOKER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (957, '井口裕香「Lostorage incited WIXOSS」', '楽曲「Lostorage」', 0, 'Lostorage', 'v1 1.45.00', 'LOSTORAGE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (958, 'Yunomi & nicamoq', 'なし', 0, 'インドア系ならトラックメイカー', 'v1 1.45.00', 'イントアケイナラトラツクメイカウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (959, 'かめりあ', 'なし', 6, 'Blackmagik Blazing', 'v1 1.45.00', 'BLACKMAGIKBLAZING');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (960, 'HaNaMiNa', 'なし', 7, 'アイジャストロック', 'v1 1.45.00', 'アイシヤストロツク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (961, 'V.I.(Various Irodorimidori)', 'なし', 7, 'SUPER RESULT BEAT vol.1', 'v1 1.45.00', 'SUPERRESULTBEATVOL1');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (962, '佐倉綾音（天宮さくら）、内田真礼（東雲初穂）、山村響（望月あざみ）、福原綾香（アナスタシア・パルマ）、早見沙織（クラリス）「新サクラ大戦」', 'PSO2・ムシキング・WLW等（主に自社コラボ）', 6, '檄！帝国華撃団＜新章＞', 'v1 1.45.00', 'ケキテイコクカケキタンシンシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (963, '歌：ひばり児童合唱団、作曲：宮内國郎、作詞：ナック企画部「チャージマン研！」', 'チャージマン研！', 0, 'チャージマン研！', 'v1 1.45.00', 'チヤウシマンケン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (964, '作曲：宮内國郎「チャージマン研！」', 'チャージマン研！', 0, '殺人レコード恐怖のメロディ', 'v1 1.45.00', 'サツシンレコウトキヨウフノメロテイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (965, 'ALI PROJECT「ローゼンメイデン」', '楽曲「禁じられた遊び」', 0, '禁じられた遊び', 'v1 1.45.00', 'キンシラレタアソヒ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (966, 'SHIKI', 'なし', 6, 'Jade Star', 'v1 1.45.00', 'JADESTAR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (967, 'イロドリミドリ', 'なし', 7, '君と、この瞬間', 'v1 1.45.00', 'キミトコノシユンカン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (968, '舞ヶ原シンセ研究会', 'なし', 7, 'We Are Us', 'v1 1.50.00', 'WEAREUS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (969, 'MK&Kanae Asaba', 'なし', 5, 'U ARE', 'v1 1.45.00', 'UARE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (970, 't+pazolite (HARDCORE TANO*C) feat.TANO*C ALL STARS', 'なし', 5, 'ハードコア・シンドローム', 'v1 1.45.00', 'ハウトコアシントロウム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (971, 'ETIA.', 'なし', 5, 'Hainuwele', 'v1 1.45.00', 'HAINUWELE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (972, 'suzu', 'なし', 5, '宿星審判', 'v1 1.45.00', 'シユクセイシンハン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (973, '曲：宮崎誠／歌：星咲 あかり(CV：赤尾 ひかる)', 'なし', 9, 'Perfect Shining!!', 'v1 1.45.00', 'PERFECTSHINING');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (974, '曲：ヒゲドライバー／歌：藤沢 柚子(CV：久保田 梨沙)', 'なし', 9, 'みんな Happy!!', 'v1 1.45.00', 'ミンナHAPPY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (975, '曲：TeddyLoid／歌：高瀬 梨緒(CV：久保 ユリカ)', 'なし', 9, 'Here We Go', 'v1 1.45.00', 'HEREWEGO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (976, '曲：Tom-H@ck／歌：結城 莉玖(CV：朝日奈 丸佳)', 'なし', 9, 'P！P！P！P！がおー!!', 'v1 1.45.00', 'PPPPカオウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (977, '仙狐（CV：和氣あず未）、シロ（CV：内田真礼）「世話やきキツネの仙狐さん」', '世話やきキツネの仙狐さん', 0, '今宵mofumofu!!', 'v1 1.45.00', 'コヨイMOFUMOFU');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (978, 'xi', 'なし', 6, 'Ascension to Heaven', 'v1 1.45.00', 'ASCENSIONTOHEAVEN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (979, 'REDALiCE & aran', '東方Project関連', 3, 'Sweet Requiem', 'v1 1.45.00', 'SWEETREQUIEM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (980, 'ビートまりお（COOL&CREATE）', '東方Project関連', 3, 'レータイスパークEx', 'v1 1.45.00', 'レウタイスハウクEX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (981, '光吉猛修の弟', 'なし', 6, '小悪魔の遊園地', 'v1 1.45.00', 'コアクマノユウエンチ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (982, '光吉猛修 VS 目黒将司', 'なし', 5, 'The Metaverse -First story of the SeelischTact-', 'v1 1.45.00', 'THEMETAVERSEFIRSTSTORYOFTHESEELISCHTACT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (983, 'カンザキイオリ', 'なし', 2, '命に嫌われている', 'v1 1.45.00', 'イノチニキラワレテイル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (984, 'DECO*27', '楽曲「乙女解剖」', 2, '乙女解剖', 'v1 1.45.00', 'オトメカイホウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (986, '菅田将暉', 'なし', 0, 'さよならエレジー', 'v1 1.45.00', 'サヨナラエレシウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (987, 'ぬゆり', 'なし', 2, 'フィクサー', 'v1 1.45.00', 'フイクサウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (988, 'ツユ', 'なし', 5, 'テリトリーバトル', 'v1 1.50.00', 'テリトリウハトル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (989, '達見 恵 featured by 佐野宏晃', 'なし', 5, 'ROAD TO DREAM', 'v1 1.50.00', 'ROADTODREAM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (990, 'TOKOTOKO（西沢さんP） feat.あやぽんず＊', 'なし', 5, '絶対トキメキデリバリー', 'v1 1.50.00', 'セツタイトキメキテリハリウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (991, 'Virtual Cat', 'なし', 5, 'Yume no hajimari', 'v1 1.50.00', 'YUMENOHAJIMARI');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (992, 'KOTONOHOUSE', 'なし', 5, 'Hey Yeah!!', 'v1 1.50.00', 'HEYYEAH');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (993, 'DIVELA feat.いゔどっと', 'なし', 5, 'B100d Hunter', 'v1 1.50.00', 'B100DHUNTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (994, 'Laur vs CK', 'なし', 5, 'Last Celebration', 'v1 1.50.00', 'LASTCELEBRATION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (997, 'USAO「Arcaea」', 'Arcaea', 6, 'Cyaegha', 'v1 1.50.00', 'CYAEGHA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (998, 'Feryquitous「Arcaea」', 'Arcaea', 6, 'Arcahv', 'v1 1.50.00', 'ARCAHV');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (999, 'かめりあ「Arcaea」', 'Arcaea', 6, 'AttraqtiA', 'v1 1.50.00', 'ATTRAQTIA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1000, 'Official髭男dism', '楽曲「Pretender」', 0, 'Pretender', 'v1 1.50.00', 'PRETENDER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1001, 'TrySail', 'なし', 0, 'ごまかし', 'v1 1.50.00', 'コマカシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1002, 'ヨルシカ', 'なし', 0, 'だから僕は音楽を辞めた', 'v1 1.50.00', 'タカラホクハオンカクヲヤメタ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1003, '福山芳樹「武装錬金」', '楽曲「真赤な誓い」', 0, '真赤な誓い', 'v1 1.50.00', 'マツカナチカイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1004, 'Eve', '楽曲「ナンセンス文学」', 2, 'ドラマツルギー', 'v1 1.50.00', 'トラマツルキウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1005, 'ナユタン星人', 'なし', 2, '彗星ハネムーン', 'v1 1.55.00', 'スイセイハネムウン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1006, '作曲：カジャ　作詞：傘村トータ　編曲：ねじ式　調声：シリア', 'なし', 2, 'アンクローズ・ヒューマン', 'v1 1.50.00', 'アンクロウスヒユウマン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1007, 'かいりきベア', '楽曲「ベノム」', 2, 'ベノム', 'v1 1.50.00', 'ヘノム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1008, 'ビートまりお × USAO', '東方Project関連', 3, 'ナイト・オブ・ナイツ (USAO Remix)', 'v1 1.50.00', 'ナイトオフナイツUSAOREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1009, 'BlackY fused with WAiKURO', 'なし', 9, 'Alea jacta est!', 'v1 1.50.00', 'ALEAJACTAEST');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1010, 'Laur', 'なし', 9, 'Viyella''s Tears', 'v1 1.50.00', 'VIYELLASTEARS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1011, 'owl＊tree／t+pazolite', 'なし', 5, 'Paqqin (tpz Despair Remix)', 'v1 1.50.00', 'PAQQINTPZDESPAIRREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1012, '藤堂 陽南袴(CV:八島 さらら)', 'なし', 7, 'Jack the GAME', 'v1 1.50.00', 'JACKTHEGAME');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1013, 'くるぶっこちゃん', 'なし', 5, '宙の隣', 'v1 1.50.00', 'ソラノトナリ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1014, 'サルケバ', 'なし', 5, 'Just You', 'v1 1.50.00', 'JUSTYOU');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1015, 'pan vs 7mai', 'なし', 5, 'Insane Gamemode', 'v1 1.50.00', 'INSANEGAMEMODE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1016, 'Potwi', 'なし', 5, 'Parad''ox', 'v1 1.50.00', 'PARADOX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1017, 'sasakure.UK VS 穴山大輔', 'なし', 5, 'ANU', 'v1 1.50.00', 'ANU');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1018, '嘘とカメレオン「虚構推理」', '楽曲「モノノケ・イン・ザ・フィクション」', 0, 'モノノケ・イン・ザ・フィクション', 'v1 1.50.00', 'モノノケインサフイクシヨン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1019, 'ピノキオピー', '初音ミク関連', 2, '愛されなくても君がいる', 'v1 1.50.00', 'アイサレナクテモキミカイル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1020, 'はるまきごはん', '初音ミク関連', 2, 'ぽかぽかの星', 'v1 1.50.00', 'ホカホカノホシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1021, 'n-buna × Orangestar', '楽曲「スターナイトスノウ」', 2, 'スターナイトスノウ', 'v1 1.50.00', 'スタウナイトスノウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1022, 'n-buna', 'なし', 2, '白ゆき', 'v1 1.50.00', 'シラユキ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1023, 'hololive IDOL PROJECT', 'ホロライブ', 0, 'Shiny Smily Story', 'v1 1.50.00', 'SHINYSMILYSTORY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1024, 'hololive IDOL PROJECT', 'ホロライブ', 0, 'キラメキライダー☆', 'v1 1.50.00', 'キラメキライタウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1025, 'ビートまりお（COOL&CREATE）', '東方Project関連', 3, '疾走あんさんぶる', 'v1 1.50.00', 'シツソウアンサンフル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1026, 'SOUND HOLIC feat. Nana Takahashi', '東方Project関連', 3, 'しゅわスパ大作戦☆', 'v1 1.50.00', 'シユワスハタイサクセン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1027, '暁Records', '東方Project関連', 3, 'LOVE EAST', 'v1 1.50.00', 'LOVEEAST');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1028, '桔梗 小夜曲(CV:原田 彩楓)', 'なし', 7, 'MELtin'' 17', 'v1 1.50.00', 'MELTIN17');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1029, '3R2 as Katzeohr', 'なし', 5, '《狂乱》 ～ Cataclysm', 'v1 1.50.00', 'キヨウランCATACLYSM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1030, 'Ring feat.SLS', 'なし', 5, '《投影》 ～ Oh My Baby Doll', 'v1 1.50.00', 'トウエイOHMYBABYDOLL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1031, '空氣載體 The AirCarrier', 'なし', 5, '《信仰》 ～ Eudaimonia', 'v1 1.50.00', 'シンコウEUDAIMONIA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1032, 'Iris', 'なし', 5, '《選別》 ～ Refuge', 'v1 1.50.00', 'センヘツREFUGE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1033, 'Spiegel vs Yukino', 'なし', 5, '《本能》 ～ ReCoda', 'v1 1.50.00', 'ホンノウRECODA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1035, 'Cranky feat.おもしろ三国志', 'なし', 5, '赤壁、大炎上！！', 'v1 1.50.00', 'セキヘキタイエンシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1036, '陰陽座', 'なし', 0, '甲賀忍法帖', 'v1 1.50.00', 'コウカニンホウチヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1037, 'イロドリミドリ', 'なし', 7, 'Everything For A Reason', 'v1 1.50.00', 'EVERYTHINGFORAREASON');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1040, 'リンカ (CV: 豊田萌絵)「グルーヴコースター」', 'グルーヴコースター', 6, 'LINK LINK FEVER!!!', 'v1 1.50.00', 'LINKLINKFEVER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1041, 'IOSYS TRAX (uno with.ちよこ)「グルーヴコースター」', 'グルーヴコースター', 6, 'DX超性能フルメタル少女', 'v1 1.50.00', 'DXチヨウセイノウフルメタルシヨウシヨ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1042, 'Dr. ARM (IOSYS)「グルーヴコースター」', 'グルーヴコースター', 6, 'SKYSCRAPER', 'v1 1.50.00', 'SKYSCRAPER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1043, 'Team Grimoire vs MASAKI「グルーヴコースター」', 'グルーヴコースター', 6, 'Lemegeton -little key of solomon-', 'v1 1.50.00', 'LEMEGETONLITTLEKEYOFSOLOMON');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1044, 'REDALiCE vs MASAKI「グルーヴコースター」', 'グルーヴコースター', 6, 'BUCHiGiRE Berserker', 'v1 1.50.00', 'BUCHIGIREBERSERKER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1045, 'shami momo（吉田優子・千代田桃）／CV：小原好美・鬼頭明里「まちカドまぞく」', '楽曲「町かどタンジェント」', 0, '町かどタンジェント', 'v1 1.55.00', 'マチカトタンシエント');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1046, '東山奈央「恋する小惑星」', '楽曲「歩いていこう！」', 0, '歩いていこう！', 'v1 1.50.00', 'アルイテイコウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1048, 'あんどうりんご（CV:今井麻美）「ぷよぷよ!!」', 'PSO2・ムシキング・WLW等（主に自社コラボ）', 6, 'ぷよぷよのうた ピコピコミックス', 'v1 1.55.00', 'フヨフヨノウタヒコヒコミツクス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1049, 'the peggies「青春ブタ野郎はバニーガール先輩の夢を見ない」', '青春ブタ野郎はバニーガール先輩の夢を見ない', 0, '君のせい', 'v1 1.50.00', 'キミノセイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1050, 'UNISON SQUARE GARDEN', '楽曲「シュガーソングとビターステップ」', 0, 'Phantom Joke', 'v1 1.50.00', 'PHANTOMJOKE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1051, 'ずっと真夜中でいいのに。', '楽曲「脳裏上のクラッカー」', 0, '脳裏上のクラッカー', 'v1 1.55.00', 'ノウリウエノクラツカウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1053, '泉こなた（CV.平野 綾）、柊かがみ（CV.加藤英美里）、柊つかさ（CV.福原香織）、高良みゆき（CV.遠藤 綾）「らき☆すた」', '楽曲「もってけ!セーラーふく」', 0, 'もってけ!セーラーふく', 'v1 1.55.00', 'モツテケセウラウフク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1054, 'まふまふ', 'なし', 2, 'サクリファイス', 'v1 1.55.00', 'サクリフアイス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1055, 'LeaF', '東方Project関連', 3, 'Wizdomiot', 'v1 1.55.00', 'WIZDOMIOT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1056, 'HaNaMiNa feat.Hana', 'なし', 7, 'なんかノイズにきこえる', 'v1 1.55.00', 'ナンカノイスニキコエル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1057, '芒崎 奏(CV:立花 理香)', 'なし', 7, 'Over Heart', 'v1 1.55.00', 'OVERHEART');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1060, '烏屋茶房 feat.利香', 'なし', 5, 'レイニーカラー・ウォーターカラー', 'v1 1.55.00', 'レイニウカラウウオウタウカラウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1061, '柏木るざりん feat.青葉りんご', 'なし', 5, 'おいでよ！ 高須らいむランド', 'v1 1.55.00', 'オイテヨタカスライムラント');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1062, '煮ル果実×びす', 'なし', 5, 'Charlatan', 'v1 1.55.00', 'CHARLATAN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1063, '李 龟琍椏 feat.娜娜苤來', 'なし', 5, '萌豚♥功夫♥大乱舞', 'v1 1.55.00', 'メントウンカンフウタウルアンウウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1064, 'Neko Hacker feat.うごくちゃん', 'なし', 5, 'つっぱれ！にゃんきー魂', 'v1 1.55.00', 'ツツハレニヤンキウタマシイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1066, 'かゆき', 'なし', 5, 'Blazing:Storm', 'v1 1.55.00', 'BLAZINGSTORM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1067, 'DECO*27', 'なし', 2, 'アンドロイドガール', 'v1 1.55.00', 'アントロイトカウル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1068, 'うたたP', '初音ミク関連', 2, 'こちら、幸福安心委員会です。', 'v1 1.55.00', 'コチラコウフクアンシンイインカイテス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1075, 'PSYQUI feat.Such', 'なし', 5, 'C & B', 'v1 1.55.00', 'CB');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1080, 'アインズ（CV：日野 聡）、カズマ（CV：福島 潤）、スバル（CV：小林裕介）、ターニャ（CV：悠木 碧）「異世界かるてっと」', '異世界かるてっと', 0, '異世界かるてっと', 'v1 1.55.00', 'イセカイカルテツト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1085, 'TANO*C Sound Team', 'なし', 6, 'BATTLE NO.1', 'v1 1.55.00', 'BATTLENO1');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1091, 'しーけー', 'なし', 6, 'クロートーと星の観測者', 'v1 1.50.00', 'クロウトウトホシノカンソクシヤ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1092, 'しらいし', 'なし', 6, '真千年女王', 'v1 1.50.00', 'シンセンネンシヨオウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1093, '茅原実里', '楽曲「Paradise Lost」', 0, 'Paradise Lost', 'v1 1.55.00', 'PARADISELOST');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1098, 'おもしろ三国志', 'なし', 6, '董卓討つべし', 'v1 1.50.00', 'トウタクウツヘシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (1099, 'ピノキオピー / 初音ミク / ワンダーランズ×ショウタイム「プロジェクトセカイ カラフルステージ！ feat. 初音ミク」', 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク', 2, 'セカイはまだ始まってすらいない', 'v1 1.50.00', 'セカイハマタハシマツテスライナイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8168, '曲：kz(livetune)／歌：オンゲキシューターズ', 'なし', 9, 'STARTLINER', 'v1 1.40.00', 'STARTLINER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8169, '高宮なすの(CV:鳴海杏子)「てーきゅう」', 'てーきゅう', 0, 'メニメニマニマニ', 'v1 1.40.00', 'メニメニマニマニ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8170, '箱部 なる(CV:M・A・O)', 'なし', 7, 'DETARAME ROCK&ROLL THEORY', 'v1 1.40.00', 'DETARAMEROCKROLLTHEORY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8171, 'DETRO a.k.a ルゼ', 'なし', 6, 'volcanic', 'v1 1.40.00', 'VOLCANIC');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8172, 'Feryquitous', 'なし', 5, 'StufeStern', 'v1 1.40.00', 'STUFESTERN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8173, 'きくお', 'なし', 5, '玩具狂奏曲 -終焉-', 'v1 1.40.00', 'カンクキヨウソウキヨクシユウエン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8174, 'HiTECH NINJA', 'なし', 5, '電光石火', 'v1 1.40.00', 'テンコウセツカ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8175, 'M2U', 'なし', 6, 'BlythE', 'v1 1.40.00', 'BLYTHE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8176, 'sun3', '東方Project関連', 3, '星の器～STAR OF ANDROMEDA', 'v1 1.40.00', 'ホシノウツワSTAROFANDROMEDA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8177, 'ARM (IOSYS)', '東方Project関連', 3, '【東方ニコカラ】秘神マターラ feat.魂音泉【IOSYS】', 'v1 1.40.00', 'トウホウニコカラヒシンマタウラFEATタマオンセンIOSYS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8178, 'ARM＋夕野ヨシミ (IOSYS) feat.miko', '東方Project関連', 3, 'ひれ伏せ愚民どもっ！', 'v1 1.40.00', 'ヒレフセクミントモツ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8179, 'Alstroemeria Records', '東方Project関連', 3, 'Dreaming', 'v1 1.40.00', 'DREAMING');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8180, 'HaNaMiNa', 'なし', 7, '【3Dサウンド】小野ちゃんが真夏のビーチでスイカを叩き割る話【イヤホン推奨】', 'v1 1.40.00', '3Dサウントオノチヤンカマナツノヒウチテスイカヲタタキワルハナシイヤホンスイシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8181, 'イロドリミドリ', 'なし', 7, 'conflict(斉唱)', 'v1 1.40.00', 'CONFLICTセイシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8182, 'Relect', 'なし', 5, 'Life', 'v1 1.45.00', 'LIFE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8183, 'Bitplane', 'なし', 6, 'チョウの標本', 'v1 1.45.00', 'チヨウノヒヨウホン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8185, 'みきとP', 'なし', 2, 'ロキ', 'v1 1.45.00', 'ロキ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8186, 'BACO', 'なし', 6, 'Dengeki Tube', 'v1 1.45.00', 'DENGEKITUBE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8187, 'セブンスシスターズ「Tokyo 7th シスターズ」', 'Tokyo 7th シスターズ・新表記', 0, 'WORLD''S END', 'v1 1.45.00', 'WORLDSEND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8188, 'Feryquitous', 'なし', 9, 'Ai Nov', 'v1 1.45.00', 'AINOV');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8189, 'HALFBY', 'なし', 5, 'bubble attack', 'v1 1.45.00', 'BUBBLEATTACK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8194, 'SYNC.ART''S feat.美里', '東方Project関連', 3, 'エピクロスの虹はもう見えない', 'v1 1.45.00', 'エヒクロスノニシハモウミエナイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8195, 'Palme', 'なし', 5, 'Blessed', 'v1 1.45.00', 'BLESSED');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8196, 'Godspeed', 'なし', 5, 'Gate of Fate', 'v1 1.45.00', 'GATEOFFATE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8197, 'ルゼ', 'なし', 6, 'ZEUS', 'v1 1.45.00', 'ZEUS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8198, 'Chu☆', 'なし', 0, '巫女みこナース・愛のテーマ', 'v1 1.50.00', 'ミコミコナウスアイノテウマ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8199, 'steμ feat.siroa「太鼓の達人」より', 'なし', 6, 'Taiko Drum Monster', 'v1 1.50.00', 'TAIKODRUMMONSTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8200, 'ゆうゆ / 篠螺悠那', '東方Project関連', 3, 'Imperishable Night 2006 (2016 Refine)', 'v1 1.50.00', 'IMPERISHABLENIGHT20062016REFINE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8201, 'nora2r', 'なし', 5, 'Fidget Dancer', 'v1 1.50.00', 'FIDGETDANCER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8202, '奥井雅美「少女革命ウテナ」', '楽曲「輪舞-revolution」', 0, '輪舞-revolution', 'v1 1.50.00', 'ロントREVOLUTION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8203, '-45', 'なし', 6, 'G e n g a o z o', 'v1 1.50.00', 'GENGAOZO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8204, 'M2U', 'なし', 6, 'Memory of Beach', 'v1 1.50.00', 'MEMORYOFBEACH');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8205, 'Bo-Xun Lin 林柏勲', 'なし', 5, '《逃避》 ～ The Deserter', 'v1 1.50.00', 'トウヒTHEDESERTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8206, '御形 アリシアナ(CV:福原 綾香)', 'なし', 7, '恋はりんりん☆あーりんベル', 'v1 1.50.00', 'コイハリンリンアウリンヘル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8207, '月見英子（CV.井口裕香）「パリピ孔明」', 'パリピ孔明', 0, 'パリピ孔明 ＣＭソング', 'v1 1.50.00', 'ハリヒコウメイCMソンク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8212, 'リンカ (CV: 豊田萌絵)「グルーヴコースター」', 'グルーヴコースター', 6, 'LINK LINK FEVER!!!', 'v1 1.55.00', 'LINKLINKFEVER');
