INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (723, 'BUMP OF CHICKEN「グランブルーファンタジー」', 'グランブルーファンタジー／Shadowverse', 0, 'GO', 'v1 1.35.00', 'GO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (724, 'ジータ（CV:金元寿子）、ルリア（CV:東山奈央）、ヴィーラ（CV:今井麻美）、マリー（CV:長谷川明子）「グランブルーファンタジー」', 'グランブルーファンタジー／Shadowverse', 0, 'キミとボクのミライ', 'v1 1.35.00', 'キミトホクノミライ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (725, '亜咲花「ゆるキャン△」', 'ゆるキャン△', 0, 'SHINY DAYS', 'v1 1.35.00', 'SHINYDAYS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (730, 'Feryquitous', 'なし', 5, 'Ai Nov', 'v1 1.35.00', 'AINOV');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (731, '中路もとめ feat.砂糖子', 'なし', 5, 'エンジェデビ', 'v1 1.35.00', 'エンシエテヒ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (732, 'PandaBoY', 'なし', 5, 'Servant of Love', 'v1 1.35.00', 'SERVANTOFLOVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (733, 'MOSAIC.WAV', 'なし', 5, 'アイリちゃんは暗黒魔導士!', 'v1 1.35.00', 'アイリチヤンハアンコクマトウシ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (734, 'HiTECH NINJA', 'なし', 5, '電光石火', 'v1 1.35.00', 'テンコウセツカ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (735, 'zts', 'なし', 5, 'strelitzia', 'v1 1.35.00', 'STRELITZIA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (285, 'ryo', 'Crypton Future Media piapro', 2, 'メルト', 'v1 1.35.00', 'メルト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (584, '分島花音「劇場版selector destructed WIXOSS」', 'なし', 0, 'Love your enemies', 'v1 1.35.00', 'LOVEYOURENEMIES');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (598, 'EarBreaker feat. Mes w/光吉猛修', 'なし', 6, 'Super Lovely (Heavenly Remix)', 'v1 1.35.00', 'SUPERLOVELYHEAVENLYREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (604, 'あまね＋ビートまりお(COOL＆CREATE)', '上海アリス幻樂団', 3, 'ウサテイ', 'v1 1.35.00', 'ウサテイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (726, 'ZAQ', '青空のラプソディ', 0, 'Sparkling Daydream', 'v1 1.35.00', 'SPARKLINGDAYDREAM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (727, 'DA PUMP', 'U.S.A.', 0, 'U.S.A.', 'v1 1.35.00', 'USA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (728, '桜高軽音部「けいおん！」', 'Don''t say "lazy"', 0, 'Don''t say "lazy"', 'v1 1.35.00', 'DONTSAYLAZY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (729, '萩原 七々瀬(CV:東城 日沙子)', 'なし', 7, 'サヨナラフリーウェイ', 'v1 1.35.00', 'サヨナラフリウウエイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (736, 'くらげP', '2017 VOCALOMAKETS Powered by Bumpy Factory Corporation.', 2, 'サヨナラチェーンソー', 'v1 1.35.00', 'サヨナラチエウンソウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (737, 'GYARI', '何でも言うことを聞いてくれるアカネチャン', 2, 'Seyana. ～何でも言うことを聞いてくれるアカネチャン～', 'v1 1.35.00', 'SEYANAナンテモイウコトヲキイテクレルアカネチヤン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (738, 'キノシタ feat. 音街ウナ', '音街ウナ', 2, 'はやくそれになりたい！', 'v1 1.35.00', 'ハヤクソレニナリタイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (739, 'カルロス袴田(サイゼP)', 'ちがう!!!', 2, 'ちがう!!!', 'v1 1.35.00', 'チカウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (740, 'バルーン', 'なし', 2, '雨とペトラ', 'v1 1.35.00', 'アメトヘトラ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (741, '森羅万象', '上海アリス幻樂団', 3, 'あうんどばいみー', 'v1 1.35.00', 'アウントハイミウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (742, 'A-One', '上海アリス幻樂団', 3, 'White Traveling Girl', 'v1 1.35.00', 'WHITETRAVELINGGIRL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (743, '暁Records', '上海アリス幻樂団', 3, 'トランスダンスアナーキー', 'v1 1.35.00', 'トランスタンスアナウキウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (744, 'Pizuya''s Cell', '上海アリス幻樂団', 3, 'ゴールドビジョン', 'v1 1.35.00', 'コウルトヒシヨン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (745, 'ARM (IOSYS)', '上海アリス幻樂団', 3, '【東方ニコカラ】秘神マターラ feat.魂音泉【IOSYS】', 'v1 1.35.00', 'トウホウニコカラヒシンマタウラFEATタマオンセンIOSYS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (746, '月鈴 白奈(CV:高野 麻里佳)', 'なし', 7, 'Ever green Never end', 'v1 1.35.00', 'EVERGREENNEVEREND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (747, '温泉むすめ 下呂美月 役 佐伯伊織「温泉むすめ」', '温泉むすめ', 0, '咲かせよ 沸かせよ バンバンBURN！', 'v1 1.35.00', 'サカセヨワカセヨハンハンBURN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (749, '削除「Arcaea」', 'Arcaea', 6, 'Fracture Ray', 'v1 1.35.00', 'FRACTURERAY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (750, 'ak+q「Arcaea」', 'Arcaea', 6, 'Axium Crisis', 'v1 1.35.00', 'AXIUMCRISIS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (751, 'Team Grimoire vs Laur「Arcaea」', 'Arcaea', 6, 'Grievous Lady', 'v1 1.35.00', 'GRIEVOUSLADY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (752, 'kanone', 'なし', 6, 'CO5M1C R4ILR0AD', 'v1 1.35.00', 'CO5M1CR4ILR0AD');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (753, 'SHIKI', 'なし', 6, 'Pure Ruby', 'v1 1.35.00', 'PURERUBY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (754, '月鈴 那知(CV:今村 彩夏)', 'なし', 7, '一世嬉遊曲‐ディヴェルティメント‐', 'v1 1.35.00', 'イツセイテイウエルテイメント');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (755, '霜月はるか', 'なし', 5, '恋のチャイム', 'v1 1.35.00', 'コイノチヤイム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (756, 'solfa feat.茶太', 'なし', 5, '逃げろ！サテライトキャンパス！！', 'v1 1.35.00', 'ニケロサテライトキヤンハス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (757, '片霧烈火', 'なし', 5, 'THE BRASS OF GOODSPEED!!', 'v1 1.35.00', 'THEBRASSOFGOODSPEED');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (758, '4U「Tokyo 7th シスターズ」', 'SEVENTH HAVEN', 0, 'TREAT OR TREAT?', 'v1 1.35.00', 'TREATORTREAT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (759, 'The QUEEN of PURPLE「Tokyo 7th シスターズ」', 'SEVENTH HAVEN', 0, 'TRIGGER', 'v1 1.35.00', 'TRIGGER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (760, 'じん', 'なし', 2, 'カゲロウデイズ', 'v1 1.35.00', 'カケロウテイス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (761, 'DECO*27', 'Crypton Future Media piapro', 2, '妄想感傷代償連盟', 'v1 1.35.00', 'モウソウカンシヨウタイシヨウレンメイ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (762, 'void (Mournfinale)', 'なし', 5, 'Everlasting Today', 'v1 1.35.00', 'EVERLASTINGTODAY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (763, '村川梨衣「ヒナまつり」', 'ヒナまつり', 0, 'Distance', 'v1 1.35.00', 'DISTANCE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (764, '庄司英徳「龍が如く２」', 'SEGA', 6, 'Outlaw''s Lullaby', 'v1 1.35.00', 'OUTLAWSLULLABY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (765, 'SoundDrive「龍が如く５　夢、叶えし者」', 'SEGA', 6, 'The Pursuit of Speed', 'v1 1.35.00', 'THEPURSUITOFSPEED');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (766, 'ナズナン星人 with せりな・あーりん(イロドリミドリ)', 'なし', 7, '光線チューニング ～なずな妄想海フェスイメージトレーニングVer.～', 'v1 1.35.00', 'コウセンチユウニンクナスナモウソウウミフエスイメウシトレウニンクVER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (768, 'sasakure.UK x DECO*27', 'Crypton Future Media piapro', 2, '39', 'v1 1.35.00', '39');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (769, '大空 遥（CV：優木かな）、比嘉かなた（CV：宮下早紀）「はるかなレシーブ」', 'はるかなレシーブ', 0, 'FLY two BLUE', 'v1 1.35.00', 'FLYTWOBLUE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (770, '大空 遥（CV：優木かな）、比嘉かなた（CV：宮下早紀）、トーマス・紅愛（CV：種﨑敦美）、トーマス・恵美理（CV：末柄里恵）「はるかなレシーブ」', 'はるかなレシーブ', 0, 'Wish me luck!!!!', 'v1 1.35.00', 'WISHMELUCK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (771, 'mommy', 'なし', 6, 'Funny Funky Freaky', 'v1 1.35.00', 'FUNNYFUNKYFREAKY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (773, 'ルゼ', 'なし', 6, 'ZEUS', 'v1 1.35.00', 'ZEUS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (774, '舞ヶ原高校軽音部', 'なし', 7, 'Agitation！', 'v1 1.35.00', 'AGITATION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (775, 'igel', 'なし', 5, '暗晦にハイライト', 'v1 1.35.00', 'アンカイニハイライト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (776, 'Sampling Masters AYA', 'なし', 5, '8-EM', 'v1 1.35.00', '8EM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (777, 'DJ Myosuke', 'なし', 5, 'Killing Rhythm', 'v1 1.35.00', 'KILLINGRHYTHM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (778, 'Void_Chords feat.MARU', 'プリンセス・プリンシパル', 0, 'The Other Side of the Wall', 'v1 1.35.00', 'THEOTHERSIDEOFTHEWALL');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (779, 'セブンスシスターズ「Tokyo 7th シスターズ」', 'SEVENTH HAVEN', 0, 'WORLD''S END', 'v1 1.35.00', 'WORLDSEND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (780, 'DIVELA', 'Crypton Future Media piapro', 2, 'METEOR', 'v1 1.35.00', 'METEOR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (781, 'wowaka', 'なし', 2, 'ワールズエンド・ダンスホール', 'v1 1.35.00', 'ワウルスエントタンスホウル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (782, 'あ～るの～と（いえろ～ぜぶら）', '上海アリス幻樂団', 3, 'Worlds End', 'v1 1.35.00', 'WORLDSEND');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (783, 'イロドリミドリ', 'なし', 7, 'Shout Our Evidence!', 'v1 1.35.00', 'SHOUTOUREVIDENCE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (784, 't+pazolite', 'なし', 5, 'YURUSHITE', 'v1 1.35.00', 'YURUSHITE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (785, 'RD-Sounds feat.中恵光城', 'なし', 5, 'ユメキキョウ', 'v1 1.35.00', 'ユメキキヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (786, '葉月ゆら', 'なし', 5, 'Black Swan Lake', 'v1 1.35.00', 'BLACKSWANLAKE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (787, '黒沢ダイスケ', 'なし', 5, 'GIGA DRIVE', 'v1 1.35.00', 'GIGADRIVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (788, 'Kai', 'なし', 5, 'Rebellion', 'v1 1.35.00', 'REBELLION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (789, '水樹奈々「魔法少女リリカルなのは Detonation」', '魔法少女リリカルなのは Detonation', 0, 'NEVER SURRENDER', 'v1 1.35.00', 'NEVERSURRENDER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (791, 'ぬるはち', '上海アリス幻樂団', 3, 'Doll Judgment', 'v1 1.35.00', 'DOLLJUDGMENT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (792, 'ARM＋夕野ヨシミ (IOSYS)', '上海アリス幻樂団', 3, 'お嫁にしなさいっ！', 'v1 1.35.00', 'オヨメニシナサイツ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (793, '豚乙女', '上海アリス幻樂団', 3, '待チ人ハ来ズ。', 'v1 1.35.00', 'マチヒトハコス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (799, 'sun3', '上海アリス幻樂団', 3, '星の器～STAR OF ANDROMEDA', 'v1 1.35.00', 'ホシノウツワSTAROFANDROMEDA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (802, '曲：kz(livetune)／歌：オンゲキシューターズ', 'なし', 5, 'STARTLINER', 'v1 1.35.00', 'STARTLINER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (803, 'siqlo', 'なし', 5, 'Vibrant Verve', 'v1 1.35.00', 'VIBRANTVERVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (804, '箱部孟徳 feat.小仏氏(イロドリミドリ)', 'なし', 7, '燃えてもエンジョイ！宛城、炎上！！', 'v1 1.35.00', 'モエテモエンシヨイエンシヨウエンシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (807, 'M2U', 'なし', 6, 'BlythE', 'v1 1.35.00', 'BLYTHE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (808, 'BUMP OF CHICKEN「グランブルーファンタジー」', 'グランブルーファンタジー／Shadowverse', 0, 'GO', 'v1 1.35.00', 'GO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8149, '上坂すみれ「ポプテピピック」', 'ポプテピピック', 0, 'POP TEAM EPIC', 'v1 1.35.00', 'POPTEAMEPIC');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8150, '池頼広「Shadowverse」', 'グランブルーファンタジー／Shadowverse', 6, 'アリサのテーマ', 'v1 1.35.00', 'アリサノテウマ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8151, 'HALFBY', 'なし', 5, 'bubble attack', 'v1 1.35.00', 'BUBBLEATTACK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8152, 'Masahiro “Godspeed” Aoki', 'なし', 5, 'Gate of Doom', 'v1 1.35.00', 'GATEOFDOOM');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8153, 'Tomggg', 'なし', 5, 'Pastel Party', 'v1 1.35.00', 'PASTELPARTY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8154, 'ビートまりお（COOL&CREATE）', '上海アリス幻樂団', 3, 'サドマミホリック', 'v1 1.35.00', 'サトマミホリツク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8155, '発熱巫女～ず', '上海アリス幻樂団', 3, 'Starlight Dance Floor', 'v1 1.35.00', 'STARLIGHTDANCEFLOOR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8156, 'Alstroemeria Records', '上海アリス幻樂団', 3, 'Dreaming', 'v1 1.35.00', 'DREAMING');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8157, '目黒将司 Remixed by 浅倉大介「ペルソナ4 ダンシング・オールナイト」', 'ATLUS', 6, 'Your Affection (Daisuke Asakura Remix)', 'v1 1.35.00', 'YOURAFFECTIONDAISUKEASAKURAREMIX');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8158, '浜渦 正志', 'なし', 5, 'The ether', 'v1 1.35.00', 'THEETHER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8159, 'POPHOLIC「龍が如く５　夢、叶えし者」', 'SEGA', 6, 'コーチンズカップ・クラシック', 'v1 1.35.00', 'コウチンスカツフクラシツク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8160, 'ピノキオピー', 'Crypton Future Media piapro', 2, '頓珍漢の宴', 'v1 1.35.00', 'トンチンカンノエン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8161, 'niki', 'なし', 2, 'WAVE', 'v1 1.35.00', 'WAVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8162, 'シンP', 'Crypton Future Media piapro', 2, '卑怯戦隊うろたんだー', 'v1 1.35.00', 'ヒキヨウセンタイウロタンタウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8163, 'sasakure.UK', 'GUMI(Megpoid)', 2, 'ぼくらの16bit戦争', 'v1 1.35.00', 'ホクラノ16BITウオウス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8164, 'xi', 'なし', 6, 'Aragami', 'v1 1.35.00', 'ARAGAMI');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8165, 'cybermiso', 'なし', 5, 'Surveiller et punir', 'v1 1.35.00', 'SURVEILLERETPUNIR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8166, 'ぬゆり', 'なし', 5, 'folern', 'v1 1.35.00', 'FOLERN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8167, 'LeaF', 'なし', 5, 'macrocosmos', 'v1 1.35.00', 'MACROCOSMOS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (772, 'sasakure.UK', 'なし', 6, 'Pangaea', 'v1 1.35.00', 'PANGAEA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (794, 'Wake Up, May''n！「異世界食堂」', '異世界食堂', 0, 'One In A Billion', 'v1 1.35.00', 'ONEINABILLION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (795, 'ぬゆり', 'なし', 2, '命ばっかり', 'v1 1.35.00', 'イノチハツカリ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (796, 'Omoi', 'なし', 2, 'テオ', 'v1 1.35.00', 'テオ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (797, '盛るP', 'Crypton Future Media piapro', 2, 'ハイセンスナンセンス', 'v1 1.35.00', 'ハイセンスナンセンス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (798, 'lumo', 'なし', 2, 'デンパラダイム', 'v1 1.35.00', 'テンハラタイム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (806, 'wa. remixed celas', 'なし', 6, '水晶世界 ～Fracture～', 'v1 1.35.00', 'スイシヨウセカイFRACTURE');
UPDATE property SET `property_value`='2020121500' WHERE  `property_key`='last_update';