INSERT INTO chusan_nameplate (id, name) VALUES (1, 'ノーマル');
INSERT INTO chusan_nameplate (id, name) VALUES (2, 'チュウニペンギン');
INSERT INTO chusan_nameplate (id, name) VALUES (3, 'AIR');
INSERT INTO chusan_nameplate (id, name) VALUES (4, 'あの日見た花の名前を僕達はまだ知らない。');
INSERT INTO chusan_nameplate (id, name) VALUES (5, 'イロドリミドリ');
INSERT INTO chusan_nameplate (id, name) VALUES (6, '初音ミク／マイディアバニー');
INSERT INTO chusan_nameplate (id, name) VALUES (7, '東方紅魔郷');
INSERT INTO chusan_nameplate (id, name) VALUES (8, '東方妖々夢');
INSERT INTO chusan_nameplate (id, name) VALUES (9, '東方永夜抄');
INSERT INTO chusan_nameplate (id, name) VALUES (10, 'ノーゲーム・ノーライフ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (11, '冴えない彼女の育てかた');
INSERT INTO chusan_nameplate (id, name) VALUES (12, '干物妹！うまるちゃん');
INSERT INTO chusan_nameplate (id, name) VALUES (14, '僕は友達が少ないNEXT 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (15, 'ミカグラ学園組曲');
INSERT INTO chusan_nameplate (id, name) VALUES (16, 'PRIUS! IMPOSSIBLE GIRLS');
INSERT INTO chusan_nameplate (id, name) VALUES (17, 'ご注文はうさぎですか？？ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (18, 'チェインクロニクル ～ヘクセイタスの閃～');
INSERT INTO chusan_nameplate (id, name) VALUES (19, 'ラグナロクオンライン');
INSERT INTO chusan_nameplate (id, name) VALUES (20, 'ばくおん!!');
INSERT INTO chusan_nameplate (id, name) VALUES (21, '蒼き鋼のアルペジオ -アルス・ノヴァ-');
INSERT INTO chusan_nameplate (id, name) VALUES (22, 'きんいろモザイク 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (23, 'Tokyo 7th シスターズ／セブンスシスターズ');
INSERT INTO chusan_nameplate (id, name) VALUES (24, 'カゲロウプロジェクト');
INSERT INTO chusan_nameplate (id, name) VALUES (25, 'イロドリミドリ(月鈴姉妹)');
INSERT INTO chusan_nameplate (id, name) VALUES (26, '東方Extra');
INSERT INTO chusan_nameplate (id, name) VALUES (27, '三者三葉 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (28, 'Angel Beats!');
INSERT INTO chusan_nameplate (id, name) VALUES (30, '言ノ葉Project 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (31, '君の名は。 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (32, '君の名は。 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (33, 'Re:ゼロから始める異世界生活 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (34, 'Re:ゼロから始める異世界生活 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (35, '化物語');
INSERT INTO chusan_nameplate (id, name) VALUES (36, '言ノ葉Project 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (37, 'NEW GAME! 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (38, 'NEW GAME! 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (39, '魔法少女まどか☆マギカ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (40, '魔法少女まどか☆マギカ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (41, 'イロドリミドリ Live!');
INSERT INTO chusan_nameplate (id, name) VALUES (42, '東方風神録');
INSERT INTO chusan_nameplate (id, name) VALUES (43, '東方Project 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (44, '結城友奈は勇者である 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (45, '結城友奈は勇者である 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (46, 'とらドラ！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (47, 'とらドラ！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (48, 'バーチャル・シンガー 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (49, 'バーチャル・シンガー 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (50, 'Hi☆sCoool! セハガール 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (51, 'PHANTASY STAR ONLINE 2 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (52, 'PHANTASY STAR ONLINE 2 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (53, 'ご注文はうさぎですか？？ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (54, 'うたわれるもの 偽りの仮面 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (55, 'うたわれるもの 偽りの仮面 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (56, 'ラストバトル');
INSERT INTO chusan_nameplate (id, name) VALUES (57, 'うたわれるもの 二人の白皇 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (58, 'うたわれるもの 二人の白皇 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (59, '戦姫絶唱シンフォギアＧ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (60, '戦姫絶唱シンフォギアＧ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (61, 'アキバ帝国');
INSERT INTO chusan_nameplate (id, name) VALUES (62, 'GEMINI -C-');
INSERT INTO chusan_nameplate (id, name) VALUES (63, 'Contrapasso -inferno-');
INSERT INTO chusan_nameplate (id, name) VALUES (64, '京急電鉄 駅名看板');
INSERT INTO chusan_nameplate (id, name) VALUES (65, 'アテインリレイション');
INSERT INTO chusan_nameplate (id, name) VALUES (66, 'エロマンガ先生 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (67, 'エロマンガ先生 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (68, 'ノラと皇女と野良猫ハート 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (69, 'ノラと皇女と野良猫ハート 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (70, 'Re:ゼロから始める異世界生活 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (71, '#コンパス 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (72, '#コンパス 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (73, '温泉むすめ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (74, '温泉むすめ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (75, '温泉むすめ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (76, 'MANIAなBEAT');
INSERT INTO chusan_nameplate (id, name) VALUES (77, '東方Extra 2');
INSERT INTO chusan_nameplate (id, name) VALUES (78, '東方Project 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (79, '東方Project 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (80, 'SeelischTact');
INSERT INTO chusan_nameplate (id, name) VALUES (81, '天使の3P！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (82, '天使の3P！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (83, 'ノーゲーム・ノーライフ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (84, 'スターダストメモリーズ');
INSERT INTO chusan_nameplate (id, name) VALUES (85, 'ツインエンジェルBREAK 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (86, 'ツインエンジェルBREAK 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (87, 'ツインエンジェルBREAK 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (88, 'ガヴリールドロップアウト 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (89, 'ガヴリールドロップアウト 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (90, 'うたわれるもの 二人の白皇 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (91, 'うたわれるもの 二人の白皇 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (94, 'Wonderland Wars 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (95, 'Wonderland Wars 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (96, 'アストラル・リベレイション');
INSERT INTO chusan_nameplate (id, name) VALUES (97, 'この素晴らしい世界に祝福を！2 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (98, 'この素晴らしい世界に祝福を！2 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (99, 'ひなこのーと 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (100, 'ひなこのーと 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (101, '福音の書');
INSERT INTO chusan_nameplate (id, name) VALUES (102, '僕は友達が少ないNEXT 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (103, 'てーきゅう 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (104, 'てーきゅう 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (105, 'NAOKI');
INSERT INTO chusan_nameplate (id, name) VALUES (106, '新甲虫王者ムシキング 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (107, '新甲虫王者ムシキング 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (108, '新甲虫王者ムシキング 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (109, '新甲虫王者ムシキング 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (111, 'KING OF BAND ''18');
INSERT INTO chusan_nameplate (id, name) VALUES (112, 'とある科学の超電磁砲S 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (113, 'とある科学の超電磁砲S 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (114, 'とある科学の超電磁砲S 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (115, 'ポプテピピック 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (116, 'ポプテピピック 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (117, 'ポプテピピック 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (118, 'G．O．D');
INSERT INTO chusan_nameplate (id, name) VALUES (119, '東方地霊殿');
INSERT INTO chusan_nameplate (id, name) VALUES (120, '東方Project 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (121, '東方Project 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (122, '元祖アイドルプロデューサー');
INSERT INTO chusan_nameplate (id, name) VALUES (123, 'りゅうおうのおしごと！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (124, 'りゅうおうのおしごと！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (125, 'ペルソナ5 ダンシング・スターナイト 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (126, 'ペルソナ5 ダンシング・スターナイト 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (127, 'ペルソナ4 ダンシング・オールナイト 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (128, 'ペルソナ4 ダンシング・オールナイト 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (129, '月鈴 白奈');
INSERT INTO chusan_nameplate (id, name) VALUES (130, 'ペルソナ3 ダンシング・ムーンナイト 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (131, 'ペルソナ3 ダンシング・ムーンナイト 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (132, 'バーチャル・シンガー 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (133, 'バーチャル・シンガー 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (134, '宇宙よりも遠い場所 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (135, '宇宙よりも遠い場所 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (136, '箱部 なる');
INSERT INTO chusan_nameplate (id, name) VALUES (137, 'ようこそ！ハッピーアニマリア');
INSERT INTO chusan_nameplate (id, name) VALUES (138, '咲-Saki-阿知賀編 episode of side-A 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (139, '咲-Saki-阿知賀編 episode of side-A 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (140, 'きんいろモザイク 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (141, 'きんいろモザイク 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (142, 'スザク');
INSERT INTO chusan_nameplate (id, name) VALUES (143, 'トリニティヴァーテックス');
INSERT INTO chusan_nameplate (id, name) VALUES (144, 'オーバーロード 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (145, 'オーバーロード 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (146, '三者三葉 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (147, '三者三葉 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (148, '天王洲 なずな');
INSERT INTO chusan_nameplate (id, name) VALUES (149, 'アトリエ ～アーランドの錬金術士～ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (150, 'アトリエ ～アーランドの錬金術士～ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (151, 'アトリエ ～アーランドの錬金術士～ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (152, '光吉 猛修／謎');
INSERT INTO chusan_nameplate (id, name) VALUES (153, '松丸 亮吾／謎');
INSERT INTO chusan_nameplate (id, name) VALUES (154, '幻想英雄伝‐目覚めし紋章の力‐');
INSERT INTO chusan_nameplate (id, name) VALUES (155, 'グランブルーファンタジー 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (156, 'グランブルーファンタジー 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (157, 'グランブルーファンタジー 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (158, 'グランブルーファンタジー 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (159, 'ゆるキャン△ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (160, 'ゆるキャン△ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (161, 'ポプテピピック 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (162, 'ポプテピピック 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (163, 'ポプテピピック 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (164, '明坂 芹菜');
INSERT INTO chusan_nameplate (id, name) VALUES (165, '東方天空璋');
INSERT INTO chusan_nameplate (id, name) VALUES (166, '東方Project 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (167, 'トリスメギストス');
INSERT INTO chusan_nameplate (id, name) VALUES (168, '天獄と魔縁');
INSERT INTO chusan_nameplate (id, name) VALUES (169, 'Arcaea 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (170, 'Arcaea 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (171, 'MIR-202【アルテミス・レナ】');
INSERT INTO chusan_nameplate (id, name) VALUES (172, 'Tokyo 7th シスターズ ～4U ＆ The QUEEN of PURPLE～ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (173, 'Tokyo 7th シスターズ ～4U ＆ The QUEEN of PURPLE～ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (174, 'Tokyo 7th シスターズ ～4U ＆ The QUEEN of PURPLE～ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (175, 'Tokyo 7th シスターズ ～4U ＆ The QUEEN of PURPLE～ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (176, 'ガヴリールドロップアウト 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (177, 'ガヴリールドロップアウト 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (178, 'ES計画');
INSERT INTO chusan_nameplate (id, name) VALUES (179, '龍が如く 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (180, '龍が如く 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (181, 'ヒナまつり 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (182, 'ヒナまつり 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (183, '小仏 凪');
INSERT INTO chusan_nameplate (id, name) VALUES (184, 'はるかなレシーブ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (185, 'はるかなレシーブ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (186, '新甲虫王者ムシキング 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (187, '新甲虫王者ムシキング 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (188, '新甲虫王者ムシキング 【7】');
INSERT INTO chusan_nameplate (id, name) VALUES (189, '新甲虫王者ムシキング 【8】');
INSERT INTO chusan_nameplate (id, name) VALUES (190, 'ノラと皇女と野良猫ハート 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (191, 'ノラと皇女と野良猫ハート 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (192, '赤月城ヴァムピーラ');
INSERT INTO chusan_nameplate (id, name) VALUES (193, '御形 アリシアナ');
INSERT INTO chusan_nameplate (id, name) VALUES (194, 'プリンセス・プリンシパル 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (195, 'プリンセス・プリンシパル 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (196, 'プリンセス・プリンシパル 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (197, 'プリンセス・プリンシパル 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (198, '温泉むすめ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (199, '温泉むすめ 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (200, '温泉むすめ 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (201, 'リリアリス・コルチカム');
INSERT INTO chusan_nameplate (id, name) VALUES (202, 'たまゆらリレイション');
INSERT INTO chusan_nameplate (id, name) VALUES (203, '魔法少女リリカルなのは Detonation 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (204, '魔法少女リリカルなのは Detonation 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (205, '魔法少女リリカルなのは Detonation 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (206, '異世界食堂 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (207, '異世界食堂 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (208, '異世界食堂 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (209, '異世界食堂 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (210, '天使の3P！ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (211, '天使の3P！ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (212, '月鈴 那知');
INSERT INTO chusan_nameplate (id, name) VALUES (213, 'アトリエ ～アーランドの錬金術士～ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (214, 'アトリエ ～アーランドの錬金術士～ 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (215, 'ショウニペンギン（AIR）');
INSERT INTO chusan_nameplate (id, name) VALUES (216, 'KING OF BAND ''19');
INSERT INTO chusan_nameplate (id, name) VALUES (217, '魔法科高校の劣等生 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (218, '魔法科高校の劣等生 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (219, '魔法科高校の劣等生 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (220, '魔法科高校の劣等生 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (221, '魔法科高校の劣等生 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (222, 'SSSS.GRIDMAN 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (223, 'SSSS.GRIDMAN 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (224, 'エロマンガ先生 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (225, '八咫烏 鋼太郎');
INSERT INTO chusan_nameplate (id, name) VALUES (226, '結月ゆかり');
INSERT INTO chusan_nameplate (id, name) VALUES (227, '紲星あかり');
INSERT INTO chusan_nameplate (id, name) VALUES (228, '琴葉 茜・葵 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (229, 'PHANTASY STAR ONLINE 2 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (230, 'PHANTASY STAR ONLINE 2 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (231, 'GN計画');
INSERT INTO chusan_nameplate (id, name) VALUES (232, 'ネコぱら 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (233, 'ネコぱら 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (234, 'ネコぱら 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (235, 'ネコぱら 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (236, 'HAR-ヒロイン09【ネレイダム】');
INSERT INTO chusan_nameplate (id, name) VALUES (237, 'とらドラ！ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (238, 'おにまむしけ');
INSERT INTO chusan_nameplate (id, name) VALUES (239, '賭ケグルイ×× 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (240, '賭ケグルイ×× 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (241, 'てーきゅう 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (242, 'てーきゅう 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (243, '五十嵐 撫子');
INSERT INTO chusan_nameplate (id, name) VALUES (244, '私に天使が舞い降りた！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (245, '私に天使が舞い降りた！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (246, 'ストライク・ザ・ブラッド 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (247, 'ストライク・ザ・ブラッド 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (248, 'この素晴らしい世界に祝福を！2 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (249, 'この素晴らしい世界に祝福を！2 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (250, 'ダオ・トッテナ');
INSERT INTO chusan_nameplate (id, name) VALUES (251, 'THE DARK SIDE NEMESIS');
INSERT INTO chusan_nameplate (id, name) VALUES (252, '東方星蓮船');
INSERT INTO chusan_nameplate (id, name) VALUES (253, '東方Project 【7】');
INSERT INTO chusan_nameplate (id, name) VALUES (254, '萩原 七々瀬');
INSERT INTO chusan_nameplate (id, name) VALUES (255, 'ゾンビランドサガ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (256, 'ゾンビランドサガ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (257, 'Hi☆sCoool! セハガール 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (258, 'Hi☆sCoool! セハガール 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (259, 'Hi☆sCoool! セハガール 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (260, 'THE LIGHT SIDE ORIGIN');
INSERT INTO chusan_nameplate (id, name) VALUES (261, 'ゴブリンスレイヤー 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (262, 'ゴブリンスレイヤー 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (263, '黒亀 北斗');
INSERT INTO chusan_nameplate (id, name) VALUES (264, '緋弾のアリアAA 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (265, '緋弾のアリアAA 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (266, 'ストライク・ザ・ブラッド 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (267, 'ストライク・ザ・ブラッド 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (268, 'リヒトシュッツェ');
INSERT INTO chusan_nameplate (id, name) VALUES (269, 'ダンベル何キロ持てる？ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (270, 'ダンベル何キロ持てる？ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (271, 'Arcaea 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (272, 'Arcaea 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (273, '暴虐のギーゼグール');
INSERT INTO chusan_nameplate (id, name) VALUES (274, '白猫プロジェクト 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (275, '白猫プロジェクト 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (276, 'アイカツオンパレード！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (277, 'アイカツオンパレード！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (278, '小野 美苗');
INSERT INTO chusan_nameplate (id, name) VALUES (279, '三賢者');
INSERT INTO chusan_nameplate (id, name) VALUES (280, '東方紅魔郷 STAGE 2');
INSERT INTO chusan_nameplate (id, name) VALUES (281, '東方Project 【8】');
INSERT INTO chusan_nameplate (id, name) VALUES (282, '渋沢 ノノ');
INSERT INTO chusan_nameplate (id, name) VALUES (283, 'チュウニペンギン＆ショウニペンギン (STAR)');
INSERT INTO chusan_nameplate (id, name) VALUES (284, '#コンパス 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (285, '#コンパス 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (286, '#コンパス 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (287, '#コンパス 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (288, 'りゅうおうのおしごと！ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (289, 'りゅうおうのおしごと！ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (290, 'ようこそ！ハッピーアニマリア2');
INSERT INTO chusan_nameplate (id, name) VALUES (291, '葛城 華');
INSERT INTO chusan_nameplate (id, name) VALUES (292, '八月のシンデレラナイン 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (293, '八月のシンデレラナイン 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (294, 'WIXOSS 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (295, 'WIXOSS 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (296, '新井 桃子');
INSERT INTO chusan_nameplate (id, name) VALUES (297, '餓音 MUSIC OF THE WAVES');
INSERT INTO chusan_nameplate (id, name) VALUES (298, '新サクラ大戦 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (299, '新サクラ大戦 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (300, 'チャージマン研！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (301, 'チャージマン研！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (302, 'チャージマン研！ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (303, 'チャージマン研！ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (305, 'MIR-201【ヘカティ・ベアトリクス】');
INSERT INTO chusan_nameplate (id, name) VALUES (306, 'オーバーロード 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (307, 'オーバーロード 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (308, '審判正義の星女神');
INSERT INTO chusan_nameplate (id, name) VALUES (309, '世話やきキツネの仙狐さん 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (310, '世話やきキツネの仙狐さん 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (311, 'テスタメントネメシス');
INSERT INTO chusan_nameplate (id, name) VALUES (312, '神位の簒奪者');
INSERT INTO chusan_nameplate (id, name) VALUES (313, 'ダンジョンに出会いを求めるのは間違っているだろうかⅡ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (314, 'ダンジョンに出会いを求めるのは間違っているだろうかⅡ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (315, '緑と水のソルナ');
INSERT INTO chusan_nameplate (id, name) VALUES (316, '青春ブタ野郎はバニーガール先輩の夢を見ない 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (317, '青春ブタ野郎はバニーガール先輩の夢を見ない 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (318, '青春ブタ野郎はバニーガール先輩の夢を見ない 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (319, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (320, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (322, 'Arcaea 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (323, 'Arcaea 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (324, 'とある科学の超電磁砲S 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (325, 'とある科学の超電磁砲S 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (326, 'DJ-MEGA');
INSERT INTO chusan_nameplate (id, name) VALUES (327, '藤堂 陽南袴');
INSERT INTO chusan_nameplate (id, name) VALUES (328, '初恋');
INSERT INTO chusan_nameplate (id, name) VALUES (329, '虚構推理 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (330, '虚構推理 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (331, '虚構推理 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (332, 'ホロライブ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (333, 'ホロライブ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (334, 'ホロライブ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (335, 'ホロライブ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (336, 'ヒナまつり 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (337, 'ヒナまつり 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (338, '宇宙よりも遠い場所 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (339, 'KING of Performai 2020 ～優勝～');
INSERT INTO chusan_nameplate (id, name) VALUES (340, 'KING of Performai 2020 ～FINALIST～');
INSERT INTO chusan_nameplate (id, name) VALUES (341, '桔梗 小夜曲');
INSERT INTO chusan_nameplate (id, name) VALUES (342, 'グルーヴコースター 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (343, 'グルーヴコースター 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (344, 'グルーヴコースター 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (345, '世にも不思議な物語');
INSERT INTO chusan_nameplate (id, name) VALUES (346, '三国志大戦 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (347, '三国志大戦 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (348, 'パリピ孔明');
INSERT INTO chusan_nameplate (id, name) VALUES (349, 'ゾンビランドサガ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (350, 'ゴブリンスレイヤー 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (351, '緋弾のアリアAA 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (352, '緋弾のアリアAA 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (353, 'MDA-01【シリウス】');
INSERT INTO chusan_nameplate (id, name) VALUES (354, '恋する小惑星 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (355, '恋する小惑星 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (356, 'ストライク・ザ・ブラッド 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (357, 'ストライク・ザ・ブラッド 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (358, 'プリンセス・プリンシパル 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (359, 'プリンセス・プリンシパル 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (360, 'ゆるキャン△ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (361, 'ゆるキャン△ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (362, '咲-Saki-阿知賀編 episode of side-A 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (363, '託されたチカラ');
INSERT INTO chusan_nameplate (id, name) VALUES (364, 'まちカドまぞく 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (365, 'まちカドまぞく 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (366, '異世界かるてっと 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (367, '異世界かるてっと 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (368, '芒崎 奏');
INSERT INTO chusan_nameplate (id, name) VALUES (369, 'ぷよぷよ!! 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (370, 'ぷよぷよ!! 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (371, '龍が如く 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (372, '東方Extra 3');
INSERT INTO chusan_nameplate (id, name) VALUES (373, '東方Project 【9】');
INSERT INTO chusan_nameplate (id, name) VALUES (374, 'ティフォン');
INSERT INTO chusan_nameplate (id, name) VALUES (375, 'ワールドヒロインズ BLOOD');
INSERT INTO chusan_nameplate (id, name) VALUES (376, 'メイドインアビス 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (377, 'メイドインアビス 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (378, '異世界食堂 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (379, 'はるかなレシーブ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (380, 'チュウニペンギン＆ショウニペンギン (AMAZON)');
INSERT INTO chusan_nameplate (id, name) VALUES (10001, '僕のヒーローアカデミア 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10002, '僕のヒーローアカデミア 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10003, 'アイドルマスター 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10004, 'アイドルマスター 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10005, 'アイドルマスター 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10006, 'アイドルマスター 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (10007, 'アイドルマスター 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (10008, 'アイドルマスター 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (10009, 'アイドルマスター 【7】');
INSERT INTO chusan_nameplate (id, name) VALUES (10010, 'アイドルマスター シンデレラガールズ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10011, 'アイドルマスター シンデレラガールズ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10012, 'アイドルマスター シンデレラガールズ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10013, 'アイドルマスター シンデレラガールズ 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (10014, 'アイドルマスター シンデレラガールズ 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (10015, 'アイドルマスター シンデレラガールズ 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (10016, 'バンドリ！ ガールズバンドパーティ！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10017, 'バンドリ！ ガールズバンドパーティ！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10018, 'バンドリ！ ガールズバンドパーティ！ 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10019, 'ひぐらしのなく頃に 業 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10020, 'ひぐらしのなく頃に 業 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10021, '東方LostWord 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10022, '東方LostWord 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10023, '乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった… 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10024, '乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった… 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10025, 'ご注文はうさぎですか？BLOOM 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10026, 'ご注文はうさぎですか？BLOOM 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10027, 'ご注文はうさぎですか？BLOOM 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10028, 'ご注文はうさぎですか？BLOOM 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (10029, 'Re:ゼロから始める異世界生活 2nd season 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10030, 'Re:ゼロから始める異世界生活 2nd season 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10031, 'ありふれた職業で世界最強 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10032, 'ありふれた職業で世界最強 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10033, 'ありふれた職業で世界最強 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10034, 'プリンセスコネクト！Re:Dive 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10035, 'プリンセスコネクト！Re:Dive 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10036, 'プリンセスコネクト！Re:Dive 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10037, '宇崎ちゃんは遊びたい！ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10038, '宇崎ちゃんは遊びたい！ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10039, '「七つの大罪 憤怒の審判」 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10040, '「七つの大罪 憤怒の審判」 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10041, '東方妖々夢 STAGE 2 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10042, '東方妖々夢 STAGE 2 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10043, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【3】');
INSERT INTO chusan_nameplate (id, name) VALUES (10044, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【4】');
INSERT INTO chusan_nameplate (id, name) VALUES (10045, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【5】');
INSERT INTO chusan_nameplate (id, name) VALUES (10046, 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (10047, '東京リベンジャーズ 【1】');
INSERT INTO chusan_nameplate (id, name) VALUES (10048, '東京リベンジャーズ 【2】');
INSERT INTO chusan_nameplate (id, name) VALUES (10050, '魔法科高校の劣等生 【6】');
INSERT INTO chusan_nameplate (id, name) VALUES (10051, '魔法科高校の劣等生 【7】');
INSERT INTO chusan_nameplate (id, name) VALUES (10052, '魔法科高校の劣等生 【8】');
INSERT INTO chusan_nameplate (id, name) VALUES (10053, '魔法科高校の劣等生 【9】');
INSERT INTO chusan_nameplate (id, name) VALUES (20001, '魔大陸の三姫霊');
INSERT INTO chusan_nameplate (id, name) VALUES (20002, 'シビュラ精霊記 ～Strive Against Fate～');
INSERT INTO chusan_nameplate (id, name) VALUES (20003, '破壊と再生　剣の後継者');
INSERT INTO chusan_nameplate (id, name) VALUES (20004, 'カゲロウリレイション');
INSERT INTO chusan_nameplate (id, name) VALUES (20005, 'HaNaMiNa');
INSERT INTO chusan_nameplate (id, name) VALUES (20006, '双炎のラストソング');
INSERT INTO chusan_nameplate (id, name) VALUES (20007, '世界襲撃♥ハネムーン');
INSERT INTO chusan_nameplate (id, name) VALUES (25001, 'イングリット・オーリック・コーネル');
INSERT INTO chusan_nameplate (id, name) VALUES (25002, 'シルヴィアス');
INSERT INTO chusan_nameplate (id, name) VALUES (25003, 'ジョニー・サイアスティン');
INSERT INTO chusan_nameplate (id, name) VALUES (25004, '魔法使いアルテラ');
INSERT INTO chusan_nameplate (id, name) VALUES (25005, '新田 ちえ');
INSERT INTO chusan_nameplate (id, name) VALUES (25006, 'MDA-21【レグルス】');
INSERT INTO chusan_nameplate (id, name) VALUES (25007, 'ジュナ・サラキア');
INSERT INTO chusan_nameplate (id, name) VALUES (25008, 'ワイズマン');
INSERT INTO chusan_nameplate (id, name) VALUES (25009, 'ヴェルゼビュートネメシス');
INSERT INTO chusan_nameplate (id, name) VALUES (30001, 'KING of Performai The 3rd ～優勝～');
INSERT INTO chusan_nameplate (id, name) VALUES (30002, 'KING of Performai The 3rd ～FINALIST～');
