INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (0, 'BUMP OF CHICKEN [cover]', 'なし', 0, '天体観測', 'v1 1.00.00', 'テンタイカンソク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (5, 'Scatman John', 'なし', 0, 'Scatman (Ski Ba Bop Ba Dop Bop)', 'v1 1.00.00', 'SCATMANSKIBABOPBADOPBOP');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (9, '→Pia-no-jaC←×葉加瀬 太郎', 'なし', 0, '情熱大陸', 'v1 1.00.00', 'シヨウネツタイリク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (10, 'The Offspring', 'なし', 6, 'All I Want', 'v1 1.00.00', 'ALLIWANT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (12, 'Linked Horizon', 'なし', 0, '紅蓮の弓矢', 'v1 1.00.00', 'クレンノユミヤ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (17, '中川 翔子', 'なし', 0, '空色デイズ', 'v1 1.00.00', 'ソライロテイス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (36, '上原 れな 「WHITE ALBUM2」', 'なし', 0, '届かない恋 ''13', 'v1 1.05.00', 'トトカナイコイ13');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (39, 'SIAM SHADE [covered by 湯毛]', 'なし', 0, '1/3の純情な感情', 'v1 1.00.00', '13ノシユンシヨウナカンシヨウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (42, 'LiSA', 'なし', 0, 'oath sign', 'v1 1.05.00', 'OATHSIGN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (43, '後ろから這いより隊G [cover]', 'なし', 0, '太陽曰く燃えよカオス', 'v1 1.00.00', 'タイヨウイワクモエヨカオス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (54, 'いきものがかり [cover]', 'なし', 0, 'ブルーバード', 'v1 1.00.00', 'フルウハウト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (56, 'JUDY AND MARY [cover]', 'なし', 0, 'そばかす', 'v1 1.00.00', 'ソハカス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (57, 'L''Arc～en～Ciel [cover]', 'なし', 0, 'STAY AWAY', 'v1 1.00.00', 'STAYAWAY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (58, '[cover]', 'なし', 0, '魂のルフラン', 'v1 1.00.00', 'タマシイノルフラン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (60, 'fripSide [cover]', 'なし', 0, 'only my railgun', 'v1 1.00.00', 'ONLYMYRAILGUN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (84, 'シド [cover]', 'なし', 0, 'V.I.P', 'v1 1.00.00', 'VIP');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (85, '湘南乃風 [cover]', 'なし', 0, '睡蓮花', 'v1 1.00.00', 'スイレンカ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (86, 'ゲスの極み乙女。', 'なし', 0, 'キラーボール', 'v1 1.00.00', 'キラウホウル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (87, '和田 光司 [cover]', 'なし', 0, 'Butter-Fly', 'v1 1.00.00', 'BUTTERFLY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (109, 'MAN WITH A MISSION', 'なし', 0, 'Emotions', 'v1 1.00.00', 'EMOTIONS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (110, 'Kalafina 「魔法少女まどか☆マギカ」', 'なし', 0, 'Magia', 'v1 1.00.00', 'MAGIA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (111, '戦場ヶ原 ひたぎ 「化物語」', 'なし', 0, 'staple stable', 'v1 1.00.00', 'STAPLESTABLE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (112, 'ST☆RISH', 'なし', 0, 'マジLOVE1000%', 'v1 1.00.00', 'マシLOVE1000');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (125, 'Rita', 'なし', 0, 'Little Busters! ～TV animation ver.～', 'v1 1.05.00', 'LITTLEBUSTERSTVANIMATIONVER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (126, '上原 れな', 'なし', 0, 'Heart To Heart', 'v1 1.05.00', 'HEARTTOHEART');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (129, 'いとう かなこ 「STEINS;GATE」', 'なし', 0, 'Hacking to the Gate', 'v1 1.00.00', 'HACKINGTOTHEGATE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (130, 'いとう かなこ 「STEINS;GATE」', 'なし', 0, 'スカイクラッドの観測者', 'v1 1.00.00', 'スカイクラツトノカンソクシヤ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (155, 'Trident 「蒼き鋼のアルペジオ ‐アルス・ノヴァ‐」', 'なし', 0, 'ブルー・フィールド', 'v1 1.00.00', 'フルウフイウルト');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (182, '小木曽 雪菜(CV:米澤 円) 「WHITE ALBUM2」', 'なし', 0, 'WHITE ALBUM Live at Campus Fes', 'v1 1.05.00', 'WHITEALBUMLIVEATCAMPUSFES');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (184, '彩菜', 'なし', 0, 'Last regrets', 'v1 1.05.00', 'LASTREGRETS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (185, '黒崎 真音 「グリザイアの果実」', 'なし', 0, '楽園の翼', 'v1 1.05.00', 'ラクエンノツハサ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (209, '春奈 るな 「冴えない彼女の育てかた」', 'なし', 0, '君色シグナル', 'v1 1.05.00', 'キミイロシクナル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (214, 'プラズマジカ 「SHOW BY ROCK!!」', 'SHOW BY ROCK!!', 0, '青春はNon-Stop！', 'v1 1.05.00', 'セイシユンハNONSTOP');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (215, 'シンガンクリムゾンズ 「SHOW BY ROCK!!」', 'SHOW BY ROCK!!', 0, 'Falling Roses', 'v1 1.05.00', 'FALLINGROSES');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (231, '沢井 美空 「冴えない彼女の育てかた」', 'なし', 0, 'カラフル。', 'v1 1.05.00', 'カラフル');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (255, 'ミルキィホームズ 「劇場版 探偵オペラ ミルキィホームズ ～逆襲のミルキィホームズ～」', '劇場版ミルキィホームズ製作委員会', 0, '激情！ミルキィ大作戦', 'v1 1.05.00', 'ケキシヨウミルキイタイサクセン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8001, 'M.S.S Project', 'なし', 5, '幾四音-Ixion-', 'v1 1.05.00', 'イクシオンIXION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8002, 'xi', 'なし', 6, 'Aragami', 'v1 1.05.00', 'ARAGAMI');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8003, 'cubesato', 'なし', 5, 'My First Phone', 'v1 1.05.00', 'MYFIRSTPHONE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8004, '長沼 英樹', 'なし', 1, 'The Concept of Love', 'v1 1.05.00', 'THECONCEPTOFLOVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8007, '削除', 'なし', 6, 'Altale', 'v1 1.05.00', 'ALTALE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8009, 'れるりり feat.ろん', 'なし', 5, 'Invitation', 'v1 1.05.00', 'INVITATION');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8010, 'あべにゅうぷろじぇくと feat.佐倉 紗織　produced by ave;new', 'なし', 5, '今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～', 'v1 1.05.00', 'イマソタテマツレオマエラヨヒメノヒメタルカツホウ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8011, 'ギガ', 'なし', 2, 'ギガンティックO.T.N', 'v1 1.05.00', 'キカンテイツクOTN');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8015, 'Sampling Masters MEGA', 'なし', 5, 'The wheel to the right', 'v1 1.05.00', 'THEWHEELTOTHERIGHT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8016, 'ふわりP', 'なし', 5, 'こころここから', 'v1 1.05.00', 'ココロココカラ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8017, 'xi', 'なし', 6, 'Aragami', 'v1 1.05.00', 'ARAGAMI');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8018, '植松 伸夫', 'なし', 5, 'Theme of SeelischTact', 'v1 1.05.00', 'THEMEOFSEELISCHTACT');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8019, 'owl＊tree', 'なし', 5, 'Teriqma', 'v1 1.05.00', 'TERIQMA');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8022, 'nora2r', 'なし', 6, 'B.B.K.K.B.K.K.', 'v1 1.05.00', 'BBKKBKK');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8023, 'sasakure.UK', 'なし', 5, '閃鋼のブリューナク', 'v1 1.05.00', 'センコウノフリユウナク');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8030, 'MOSAIC.WAV', 'なし', 5, 'とーきょー全域★アキハバラ？', 'v1 1.05.00', 'トウキヨウセンイキアキハハラ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8032, '片霧烈火オンザみんマンション', 'なし', 5, 'ＧＯ！ＧＯ！ラブリズム♥', 'v1 1.05.00', 'GOGOラフリスム');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8035, 'sasakure.UK', 'なし', 6, 'Jack-the-Ripper◆', 'v1 1.10.00', 'JACKTHERIPPER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8036, 'Silver Forest', '上海アリス幻樂団', 3, 'sweet little sister', 'v1 1.10.00', 'SWEETLITTLESISTER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8037, 'Tatsh', 'なし', 5, 'GEMINI -C-', 'v1 1.10.00', 'GEMINIC');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8038, '浜渦 正志', 'なし', 5, 'The ether', 'v1 1.10.00', 'THEETHER');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8039, 'xi', 'なし', 6, 'FREEDOM DiVE', 'v1 1.10.00', 'FREEDOMDIVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8040, 'sasakure.UK', 'GUMI(Megpoid)', 2, 'ぼくらの16bit戦争', 'v1 1.10.00', 'ホクラノ16BITウオウス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8041, '削除', 'なし', 5, 'Cyberozar', 'v1 1.10.00', 'CYBEROZAR');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8042, 'Morrigan', 'なし', 5, 'GOLDEN RULE', 'v1 1.10.00', 'GOLDENRULE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8044, 'Masayoshi Minoshima', '上海アリス幻樂団', 3, 'Bad Apple!! feat.nomico', 'v1 1.10.00', 'BADAPPLEFEATNOMICO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8050, 't+pazolite', 'なし', 5, 'Infantoon Fantasy', 'v1 1.10.00', 'INFANTOONFANTASY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8052, '豚乙女', 'なし', 5, '明るい未来', 'v1 1.10.00', 'アカルイミライ');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8054, 't+pazolite', 'なし', 5, 'Contrapasso -inferno-', 'v1 1.10.00', 'CONTRAPASSOINFERNO');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8056, '箱部 なる(CV:M・A・O)', 'なし', 7, 'DETARAME ROCK&ROLL THEORY', 'v1 1.10.00', 'DETARAMEROCKROLLTHEORY');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8060, '長沼 英樹', 'なし', 1, 'The Concept of Love', 'v1 1.10.00', 'THECONCEPTOFLOVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8061, 'Masayoshi Minoshima feat.Mei Ayakura', 'なし', 5, 'SNIPE WHOLE', 'v1 1.10.00', 'SNIPEWHOLE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8062, 'wowaka', 'なし', 2, '裏表ラバーズ', 'v1 1.10.00', 'ウラオモテラハウス');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8068, 'Mitchie M', 'なし', 2, 'FREELY TOMORROW', 'v1 1.15.00', 'FREELYTOMORROW');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8071, 'イロドリミドリ', 'なし', 7, 'Change Our MIRAI！', 'v1 1.15.00', 'CHANGEOURMIRAI');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8076, '佐咲紗花「ばくおん!!」', 'おりもとみまな（ヤングチャンピオン烈）／ばくおん!!製作委員会', 0, 'FEEL×ALIVE', 'v1 1.15.00', 'FEELALIVE');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8077, '佐倉羽音(CV.上田麗奈)、鈴乃木凜(CV.東山奈央)、天野恩紗(CV.内山夕実)、三ノ輪聖(CV.山口立花子)「ばくおん!!」', 'おりもとみまな（ヤングチャンピオン烈）／ばくおん!!製作委員会', 0, 'ぶぉん！ぶぉん！らいど・おん！', 'v1 1.15.00', 'フオンフオンライトオン');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8083, 'ソニック カラーズ', 'なし', 1, 'Reach for the Stars', 'v1 1.15.00', 'REACHFORTHESTARS');
INSERT INTO chuni_music (music_id, artist_name, copyright, genre, name, release_version, sort_name) VALUES (8088, 'そらる・ろん×れるりり', 'なし', 8, '言ノ葉カルマ', 'v1 1.15.00', 'コトノハカルマ');

INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2465, 0, true, 2, 0, 0);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2466, 1, true, 4, 0, 0);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2467, 2, true, 7, 80, 0);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2468, 3, true, 9, 50, 0);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2469, 4, false, 0, 0, 0);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2470, 0, true, 2, 0, 5);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2471, 1, true, 5, 0, 5);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2472, 2, true, 9, 40, 5);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2473, 3, true, 11, 30, 5);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2474, 4, false, 0, 0, 5);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2475, 0, true, 3, 0, 9);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2476, 1, true, 6, 0, 9);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2477, 2, true, 8, 30, 9);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2478, 3, true, 12, 0, 9);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2479, 4, false, 0, 0, 9);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2480, 0, true, 3, 0, 10);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2481, 1, true, 6, 0, 10);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2482, 2, true, 8, 60, 10);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2483, 3, true, 11, 70, 10);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2484, 4, false, 0, 0, 10);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2485, 0, true, 3, 0, 12);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2486, 1, true, 6, 0, 12);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2487, 2, true, 9, 20, 12);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2488, 3, true, 10, 60, 12);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2489, 4, false, 0, 0, 12);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2490, 0, true, 2, 0, 17);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2491, 1, true, 4, 0, 17);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2492, 2, true, 8, 20, 17);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2493, 3, true, 11, 20, 17);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2494, 4, false, 0, 0, 17);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2495, 0, true, 2, 0, 36);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2496, 1, true, 5, 0, 36);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2497, 2, true, 8, 90, 36);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2498, 3, true, 11, 0, 36);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2499, 4, false, 0, 0, 36);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2500, 0, true, 2, 0, 39);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2501, 1, true, 4, 0, 39);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2502, 2, true, 7, 60, 39);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2503, 3, true, 9, 30, 39);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2504, 4, false, 0, 0, 39);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2505, 0, true, 2, 0, 42);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2506, 1, true, 5, 0, 42);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2507, 2, true, 8, 20, 42);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2508, 3, true, 11, 60, 42);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2509, 4, false, 0, 0, 42);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2510, 0, true, 2, 0, 43);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2511, 1, true, 4, 0, 43);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2512, 2, true, 8, 10, 43);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2513, 3, true, 10, 80, 43);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2514, 4, false, 0, 0, 43);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2515, 0, true, 2, 0, 54);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2516, 1, true, 5, 0, 54);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2517, 2, true, 8, 30, 54);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2518, 3, true, 10, 60, 54);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2519, 4, false, 0, 0, 54);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2520, 0, true, 2, 0, 56);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2521, 1, true, 4, 0, 56);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2522, 2, true, 8, 40, 56);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2523, 3, true, 11, 0, 56);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2524, 4, false, 0, 0, 56);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2525, 0, true, 3, 0, 57);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2526, 1, true, 6, 0, 57);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2527, 2, true, 8, 40, 57);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2528, 3, true, 9, 70, 57);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2529, 4, false, 0, 0, 57);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2530, 0, true, 2, 0, 58);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2531, 1, true, 5, 0, 58);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2532, 2, true, 7, 70, 58);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2533, 3, true, 9, 40, 58);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2534, 4, false, 0, 0, 58);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2535, 0, true, 2, 0, 60);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2536, 1, true, 5, 0, 60);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2537, 2, true, 8, 80, 60);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2538, 3, true, 11, 40, 60);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2539, 4, false, 0, 0, 60);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2540, 0, true, 3, 0, 84);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2541, 1, true, 6, 0, 84);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2542, 2, true, 8, 80, 84);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2543, 3, true, 10, 40, 84);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2544, 4, false, 0, 0, 84);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2545, 0, true, 3, 0, 85);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2546, 1, true, 5, 0, 85);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2547, 2, true, 7, 50, 85);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2548, 3, true, 10, 30, 85);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2549, 4, false, 0, 0, 85);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2550, 0, true, 3, 0, 86);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2551, 1, true, 5, 0, 86);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2552, 2, true, 7, 20, 86);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2553, 3, true, 10, 0, 86);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2554, 4, false, 0, 0, 86);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2555, 0, true, 3, 0, 87);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2556, 1, true, 5, 0, 87);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2557, 2, true, 8, 70, 87);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2558, 3, true, 10, 40, 87);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2559, 4, false, 0, 0, 87);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2560, 0, true, 3, 0, 109);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2561, 1, true, 5, 0, 109);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2562, 2, true, 8, 80, 109);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2563, 3, true, 10, 70, 109);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2564, 4, false, 0, 0, 109);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2565, 0, true, 2, 0, 110);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2566, 1, true, 5, 0, 110);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2567, 2, true, 9, 10, 110);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2568, 3, true, 11, 20, 110);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2569, 4, false, 0, 0, 110);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2570, 0, true, 2, 0, 111);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2571, 1, true, 5, 0, 111);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2572, 2, true, 9, 60, 111);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2573, 3, true, 11, 30, 111);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2574, 4, false, 0, 0, 111);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2575, 0, true, 2, 0, 112);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2576, 1, true, 5, 0, 112);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2577, 2, true, 8, 20, 112);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2578, 3, true, 11, 0, 112);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2579, 4, false, 0, 0, 112);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2580, 0, true, 3, 0, 125);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2581, 1, true, 5, 0, 125);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2582, 2, true, 8, 40, 125);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2583, 3, true, 11, 0, 125);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2584, 4, false, 0, 0, 125);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2585, 0, true, 2, 0, 126);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2586, 1, true, 5, 0, 126);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2587, 2, true, 8, 30, 126);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2588, 3, true, 11, 30, 126);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2589, 4, false, 0, 0, 126);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2590, 0, true, 2, 0, 129);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2591, 1, true, 5, 0, 129);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2592, 2, true, 9, 50, 129);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2593, 3, true, 11, 20, 129);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2594, 4, false, 0, 0, 129);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2595, 0, true, 3, 0, 130);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2596, 1, true, 6, 0, 130);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2597, 2, true, 9, 40, 130);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2598, 3, true, 11, 70, 130);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2599, 4, false, 0, 0, 130);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2600, 0, true, 2, 0, 155);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2601, 1, true, 5, 0, 155);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2602, 2, true, 9, 70, 155);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2603, 3, true, 10, 70, 155);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2604, 4, false, 0, 0, 155);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2605, 0, true, 2, 0, 182);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2606, 1, true, 4, 0, 182);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2607, 2, true, 7, 50, 182);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2608, 3, true, 10, 10, 182);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2609, 4, false, 0, 0, 182);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2610, 0, true, 1, 0, 184);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2611, 1, true, 4, 0, 184);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2612, 2, true, 7, 70, 184);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2613, 3, true, 10, 0, 184);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2614, 4, false, 0, 0, 184);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2615, 0, true, 2, 0, 185);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2616, 1, true, 6, 0, 185);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2617, 2, true, 8, 70, 185);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2618, 3, true, 11, 20, 185);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2619, 4, false, 0, 0, 185);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2620, 0, true, 3, 0, 209);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2621, 1, true, 5, 0, 209);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2622, 2, true, 9, 30, 209);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2623, 3, true, 11, 20, 209);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2624, 4, false, 0, 0, 209);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2625, 0, true, 2, 0, 214);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2626, 1, true, 5, 0, 214);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2627, 2, true, 9, 90, 214);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2628, 3, true, 11, 80, 214);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2629, 4, false, 0, 0, 214);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2630, 0, true, 3, 0, 215);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2631, 1, true, 6, 0, 215);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2632, 2, true, 9, 60, 215);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2633, 3, true, 12, 40, 215);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2634, 4, false, 0, 0, 215);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2635, 0, true, 3, 0, 231);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2636, 1, true, 4, 0, 231);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2637, 2, true, 8, 30, 231);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2638, 3, true, 11, 0, 231);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2639, 4, false, 0, 0, 231);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2640, 0, true, 3, 0, 255);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2641, 1, true, 5, 0, 255);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2642, 2, true, 8, 70, 255);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2643, 3, true, 11, 0, 255);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2644, 4, false, 0, 0, 255);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2645, 0, false, 0, 0, 8001);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2646, 1, false, 0, 0, 8001);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2647, 2, false, 0, 0, 8001);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2648, 3, false, 0, 0, 8001);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2649, 4, true, 0, 0, 8001);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2650, 0, false, 0, 0, 8002);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2651, 1, false, 0, 0, 8002);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2652, 2, false, 0, 0, 8002);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2653, 3, false, 0, 0, 8002);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2654, 4, true, 0, 0, 8002);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2655, 0, false, 0, 0, 8003);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2656, 1, false, 0, 0, 8003);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2657, 2, false, 0, 0, 8003);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2658, 3, false, 0, 0, 8003);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2659, 4, true, 0, 0, 8003);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2660, 0, false, 0, 0, 8004);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2661, 1, false, 0, 0, 8004);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2662, 2, false, 0, 0, 8004);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2663, 3, false, 0, 0, 8004);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2664, 4, true, 0, 0, 8004);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2665, 0, false, 0, 0, 8007);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2666, 1, false, 0, 0, 8007);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2667, 2, false, 0, 0, 8007);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2668, 3, false, 0, 0, 8007);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2669, 4, true, 0, 0, 8007);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2670, 0, false, 0, 0, 8009);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2671, 1, false, 0, 0, 8009);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2672, 2, false, 0, 0, 8009);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2673, 3, false, 0, 0, 8009);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2674, 4, true, 0, 0, 8009);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2675, 0, false, 0, 0, 8010);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2676, 1, false, 0, 0, 8010);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2677, 2, false, 0, 0, 8010);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2678, 3, false, 0, 0, 8010);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2679, 4, true, 0, 0, 8010);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2680, 0, false, 0, 0, 8011);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2681, 1, false, 0, 0, 8011);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2682, 2, false, 0, 0, 8011);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2683, 3, false, 0, 0, 8011);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2684, 4, true, 0, 0, 8011);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2685, 0, false, 0, 0, 8015);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2686, 1, false, 0, 0, 8015);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2687, 2, false, 0, 0, 8015);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2688, 3, false, 0, 0, 8015);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2689, 4, true, 0, 0, 8015);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2690, 0, false, 0, 0, 8016);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2691, 1, false, 0, 0, 8016);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2692, 2, false, 0, 0, 8016);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2693, 3, false, 0, 0, 8016);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2694, 4, true, 0, 0, 8016);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2695, 0, false, 0, 0, 8017);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2696, 1, false, 0, 0, 8017);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2697, 2, false, 0, 0, 8017);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2698, 3, false, 0, 0, 8017);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2699, 4, true, 0, 0, 8017);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2700, 0, false, 0, 0, 8018);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2701, 1, false, 0, 0, 8018);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2702, 2, false, 0, 0, 8018);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2703, 3, false, 0, 0, 8018);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2704, 4, true, 0, 0, 8018);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2705, 0, false, 0, 0, 8019);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2706, 1, false, 0, 0, 8019);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2707, 2, false, 0, 0, 8019);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2708, 3, false, 0, 0, 8019);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2709, 4, true, 0, 0, 8019);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2710, 0, false, 0, 0, 8022);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2711, 1, false, 0, 0, 8022);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2712, 2, false, 0, 0, 8022);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2713, 3, false, 0, 0, 8022);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2714, 4, true, 0, 0, 8022);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2715, 0, false, 0, 0, 8023);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2716, 1, false, 0, 0, 8023);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2717, 2, false, 0, 0, 8023);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2718, 3, false, 0, 0, 8023);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2719, 4, true, 0, 0, 8023);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2720, 0, false, 0, 0, 8030);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2721, 1, false, 0, 0, 8030);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2722, 2, false, 0, 0, 8030);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2723, 3, false, 0, 0, 8030);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2724, 4, true, 0, 0, 8030);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2725, 0, false, 0, 0, 8032);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2726, 1, false, 0, 0, 8032);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2727, 2, false, 0, 0, 8032);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2728, 3, false, 0, 0, 8032);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2729, 4, true, 0, 0, 8032);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2730, 0, false, 0, 0, 8035);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2731, 1, false, 0, 0, 8035);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2732, 2, false, 0, 0, 8035);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2733, 3, false, 0, 0, 8035);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2734, 4, true, 0, 0, 8035);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2735, 0, false, 0, 0, 8036);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2736, 1, false, 0, 0, 8036);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2737, 2, false, 0, 0, 8036);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2738, 3, false, 0, 0, 8036);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2739, 4, true, 0, 0, 8036);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2740, 0, false, 0, 0, 8037);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2741, 1, false, 0, 0, 8037);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2742, 2, false, 0, 0, 8037);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2743, 3, false, 0, 0, 8037);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2744, 4, true, 0, 0, 8037);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2745, 0, false, 0, 0, 8038);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2746, 1, false, 0, 0, 8038);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2747, 2, false, 0, 0, 8038);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2748, 3, false, 0, 0, 8038);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2749, 4, true, 0, 0, 8038);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2750, 0, false, 0, 0, 8039);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2751, 1, false, 0, 0, 8039);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2752, 2, false, 0, 0, 8039);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2753, 3, false, 0, 0, 8039);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2754, 4, true, 0, 0, 8039);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2755, 0, false, 0, 0, 8040);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2756, 1, false, 0, 0, 8040);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2757, 2, false, 0, 0, 8040);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2758, 3, false, 0, 0, 8040);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2759, 4, true, 0, 0, 8040);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2760, 0, false, 0, 0, 8041);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2761, 1, false, 0, 0, 8041);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2762, 2, false, 0, 0, 8041);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2763, 3, false, 0, 0, 8041);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2764, 4, true, 0, 0, 8041);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2765, 0, false, 0, 0, 8042);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2766, 1, false, 0, 0, 8042);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2767, 2, false, 0, 0, 8042);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2768, 3, false, 0, 0, 8042);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2769, 4, true, 0, 0, 8042);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2770, 0, false, 0, 0, 8044);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2771, 1, false, 0, 0, 8044);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2772, 2, false, 0, 0, 8044);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2773, 3, false, 0, 0, 8044);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2774, 4, true, 0, 0, 8044);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2775, 0, false, 0, 0, 8050);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2776, 1, false, 0, 0, 8050);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2777, 2, false, 0, 0, 8050);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2778, 3, false, 0, 0, 8050);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2779, 4, true, 0, 0, 8050);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2780, 0, false, 0, 0, 8052);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2781, 1, false, 0, 0, 8052);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2782, 2, false, 0, 0, 8052);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2783, 3, false, 0, 0, 8052);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2784, 4, true, 0, 0, 8052);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2785, 0, false, 0, 0, 8054);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2786, 1, false, 0, 0, 8054);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2787, 2, false, 0, 0, 8054);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2788, 3, false, 0, 0, 8054);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2789, 4, true, 0, 0, 8054);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2790, 0, false, 0, 0, 8056);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2791, 1, false, 0, 0, 8056);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2792, 2, false, 0, 0, 8056);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2793, 3, false, 0, 0, 8056);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2794, 4, true, 0, 0, 8056);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2795, 0, false, 0, 0, 8060);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2796, 1, false, 0, 0, 8060);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2797, 2, false, 0, 0, 8060);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2798, 3, false, 0, 0, 8060);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2799, 4, true, 0, 0, 8060);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2800, 0, false, 0, 0, 8061);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2801, 1, false, 0, 0, 8061);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2802, 2, false, 0, 0, 8061);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2803, 3, false, 0, 0, 8061);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2804, 4, true, 0, 0, 8061);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2805, 0, false, 0, 0, 8062);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2806, 1, false, 0, 0, 8062);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2807, 2, false, 0, 0, 8062);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2808, 3, false, 0, 0, 8062);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2809, 4, true, 0, 0, 8062);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2810, 0, false, 0, 0, 8068);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2811, 1, false, 0, 0, 8068);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2812, 2, false, 0, 0, 8068);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2813, 3, false, 0, 0, 8068);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2814, 4, true, 0, 0, 8068);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2815, 0, false, 0, 0, 8071);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2816, 1, false, 0, 0, 8071);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2817, 2, false, 0, 0, 8071);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2818, 3, false, 0, 0, 8071);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2819, 4, true, 0, 0, 8071);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2820, 0, false, 0, 0, 8076);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2821, 1, false, 0, 0, 8076);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2822, 2, false, 0, 0, 8076);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2823, 3, false, 0, 0, 8076);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2824, 4, true, 0, 0, 8076);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2825, 0, false, 0, 0, 8077);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2826, 1, false, 0, 0, 8077);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2827, 2, false, 0, 0, 8077);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2828, 3, false, 0, 0, 8077);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2829, 4, true, 0, 0, 8077);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2830, 0, false, 0, 0, 8083);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2831, 1, false, 0, 0, 8083);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2832, 2, false, 0, 0, 8083);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2833, 3, false, 0, 0, 8083);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2834, 4, true, 0, 0, 8083);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2835, 0, false, 0, 0, 8088);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2836, 1, false, 0, 0, 8088);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2837, 2, false, 0, 0, 8088);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2838, 3, false, 0, 0, 8088);
INSERT INTO chuni_music_level (id, diff, enable, level, level_decimal, music_id) VALUES (2839, 4, true, 0, 0, 8088);